{
  "hash": "f5e6d035472741aed61baa1d3f9e1428",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Shipping Failure Mode of the Nitrogen-Purged Optical Assembly\"\nsubtitle: \"Return-Leg Underpressure Following Irreversible Mass Loss\"\nauthor: \"Opto-Mechanical Engineering Group\"\ndate: 2026-04-15\ndate-format: \"MMMM D, YYYY\"\nabstract: |\n  The nitrogen-purged optical assembly fails by return-leg underpressure\n  after irreversible nitrogen mass loss during air transport, not by\n  outbound overpressure. Closed-form thresholds and a quasi-static\n  shipping-cycle model establish that the conservative as-built rigid\n  volume ($V_{fixed} \\approx 35\\;\\text{L}$) with the 2 psig Swagelok\n  check valve is nominally safe under single-flight ideal assumptions:\n  the bag absorbs the full excursion without venting and the return-leg\n  pressure remains nonnegative. However, the as-built valve requires up\n  to 2 psig reverse differential to reseat, and the model produces less\n  than 2 psig backpressure across the full operating envelope. The valve\n  therefore remains open after first cracking. Multi-leg shipments\n  compound mass loss beyond the single-flight prediction, and handling\n  of the unsupported foil bag drives additional gas exchange through the\n  unseated valve. These mechanisms — valve non-reseat, multi-leg\n  ratcheting, and handling-driven breathing — are not captured by the\n  single-flight model and represent non-conservative gaps. Removal or\n  permanent sealing of the bag vent eliminates the irreversible mass-loss\n  pathway; the existing 0.5 bar circuit relief provides sufficient\n  overpressure protection at any volume and any number of flight legs.\nkeywords:\n  - nitrogen purge\n  - shipping qualification\n  - compliance volume\n  - sub-atmospheric pressure\n  - optical contamination\n  - thermodynamic failure analysis\n---\n\n# Summary {#sec-summary}\n\nThe shipping concept for the nitrogen-purged optical assembly relies on a foil compliance bag and an outward-only check valve. A design review focused on the high-pressure side of the transport cycle concludes that the present 0.5 bar safety relief valve handles outbound overpressure with margin. That conclusion is correct on its own terms, but it does not address the actual failure mode.\n\nThe actual failure is **return-leg underpressure** following **irreversible nitrogen mass loss**. During ascent and heating, the internal nitrogen expands. If the bag saturates before reaching its maximum volume, internal pressure rises and the outward-only valve vents nitrogen to ambient. This is a one-way thermodynamic event: the retained mole inventory is permanently reduced. On descent and cooling the bag contracts, and if the bag fully collapses while the remaining nitrogen is insufficient to fill the rigid connected volume at the return temperature, the internal pressure falls below ambient. The distributed seal network of the manifolded assembly is positive-pressure energized. It is not qualified for sub-atmospheric internal conditions. Atmospheric ingress through any joint or seal is then thermodynamically favored.\n\nThe mechanism does not depend on valve back-leakage or bag leakage. Even an ideal outward-only valve and an ideal zero-stiffness bag exhibit this failure once the rigid connected volume exceeds a critical threshold. Two closed-form expressions govern the design space: the largest rigid volume that avoids any outbound venting in Eq. @eq-no-vent, and the largest rigid volume that still returns nonnegative after venting in Eq. @eq-return-threshold. For the present 22 L bag and the standard ICAO/FAA shipping envelope, these thresholds are approximately **15.28 L** and **52.55 L** for ideal outward venting. A conservative estimate places the rigid nitrogen volume of the production hardware at $V_{fixed} \\approx 35\\;\\text{L}$. At 35 L the system lies above the no-vent threshold and will vent on the outbound leg, but remains below the nonnegative-return threshold under both the ideal-vent and 2 psig screening cases (@tbl-thresholds). A traceable volume measurement is required to confirm this estimate and formally close **FND-SH-003**.\n\nA subsequent analysis in @sec-upper-bound derives an analytical upper bound on the maximum overpressure that can develop during any single-flight cycle, and demonstrates that the existing 0.5 bar circuit relief valve cannot open under physically realizable cargo temperatures. Under the validity conditions in @sec-validity-conditions, that bound supports removing the bag vent as a way to eliminate the irreversible mass-loss pathway. The explicit decision framing for that recommendation appears in @sec-decision-status.\n\n# System Description {#sec-system}\n\nThe shipped article is a manifolded optical assembly composed of multiple sealed aluminum optical modules connected to a common nitrogen space through PFA interconnect tubing and intake/exhaust manifolds. The total internal nitrogen space is the sum of the module interiors, the interconnect tubing, the manifold volumes, and the shipping-time compliance bag. All of these volumes communicate freely through the manifold network and behave thermodynamically as a single connected gas volume.\n\nIn operation, a continuous nitrogen purge maintains positive gauge pressure throughout the assembly. Every joint and seal in the assembly is positive-pressure energized: the seating force comes from the positive internal-to-ambient pressure differential. These seals are not qualified for sub-atmospheric internal conditions. If the internal pressure ever falls below ambient, seating force is lost and the seal admits ambient air through the same path it normally exhausts nitrogen.\n\nDuring shipping, the continuous purge is unavailable. The assembly is sealed at atmospheric pressure with a fixed initial nitrogen mass, and two passive elements are responsible for managing pressure excursions across the transport cycle:\n\n1.  **Foil compliance bag** -- a CALDRY 1500 multilayer foil reservoir that can expand and contract between approximately zero and 22 L. The foil is geometrically compliant but not elastically compliant: it unfolds and refolds between hard geometric limits with negligible restoring force across its usable range.\n\n2.  **Outward-only check/vent valve** -- a Swagelok 6L-CW4VR4-P high-purity welded check valve. It permits nitrogen to escape if the internal pressure exceeds ambient by the valve's cracking threshold, but does not admit ambient flow inward. A separate 0.5 bar gauge safety relief valve remains on the main assembly per the European pressure equipment directive.\n\n@tbl-vent-valve lists the relevant specifications for the breather-path check valve.\n\n::: {#tbl-vent-valve tbl-colwidths=\"[40,60]\"}\n| Parameter | Value |\n|:---------------------------|:----------------------------------------------|\n| Part number | Swagelok 6L-CW4VR4-P |\n| Description | 316L SS high-purity welded check valve, SC-01 cleaned |\n| Cracking pressure | 2 psig (0.14 bar) |\n| Flow coefficient $C_v$ | 0.7 |\n| Connections | 1/4 in. integral male VCR (inlet and outlet) |\n| Seal material | Fluorocarbon FKM |\n| Wetted surface finish | Ra 8 $\\mu$in (0.20 $\\mu$m), electropolished |\n| Pressure rating | 3000 psig at 100 °F (206 bar at 37 °C) |\n\nBreather-path check valve specifications. The 2 psig cracking pressure is the threshold used in the \"vent threshold 2 psig\" screening cases in @tbl-thresholds.\n:::\n\n@fig-three-regimes shows the baseline shipping cycle for the estimated 35 L rigid volume with the as-built 2 psig valve. Under these parameters the bag absorbs the full excursion without venting and no harmful pressure differential develops — the safe baseline. @fig-ideal-vent-cycle in @sec-actual-mechanism shows how the failure sequence emerges at larger rigid volumes or lower vent thresholds.\n\n::: {#cell-fig-three-regimes .cell execution_count=1}\n\n::: {.cell-output .cell-output-display}\n![Two-leg shipping flight cycle for the estimated 35 L rigid volume with the as-built 2 psig Swagelok valve. Top: cabin altitude profile showing the two flight legs with a ground turnaround. Middle: ambient and internal pressure — the curves overlap throughout, confirming the bag absorbs the full excursion without venting. Bottom: bag volume approaches but does not exceed the 22 L saturation limit. Compare with @fig-ideal-vent-cycle, which shows the failure sequence at larger rigid volumes.](failure-mechanism_files/figure-html/fig-three-regimes-output-1.svg){#fig-three-regimes fig-alt='Three-panel time-series plot. Top panel shows equivalent cabin altitude versus time, rising to 8000 feet during two flight legs with a ground turnaround between them. Middle panel shows ambient pressure (dashed) and internal pressure (solid) versus time; the two curves overlap almost perfectly, indicating no harmful pressure differential develops. Bottom panel shows bag volume versus time, rising from 11 liters toward the 22-liter saturation limit during cruise and contracting after landing. Vertical lines separate ten flight phases, each labeled at the top of the figure.'}\n:::\n:::\n\n\n# Transport Envelope {#sec-envelope}\n\n@tbl-shipping-spec summarizes the official shipping and storage requirements that bound the transport design space. The pressure-gradient requirement is satisfied by compliance with standard commercial air-freight cabin-altitude limits.\n\n::: {#tbl-shipping-spec tbl-colwidths=\"[35,35,30]\"}\n| Requirement | Value | Source |\n|:----------------------|:------------------------|:------------------------|\n| Temperature range | 10 °C to 40 °C | Shipping specification |\n| Maximum pressure gradient | Aerial transport | Shipping specification |\n| Maximum acceleration | 10 g | Shipping specification |\n\nOfficial shipping and storage requirements for the nitrogen-purged optical assembly.\n:::\n\nThe transport state space derived from these requirements and the applicable regulatory limits is summarized in @tbl-transport-envelope.\n\n::: {#tbl-transport-envelope tbl-colwidths=\"[35,30,35]\"}\n| Parameter | Value | Basis |\n|:----------------------|:------------------------|:------------------------|\n| Temperature range | 10 °C to 40 °C | Shipping specification |\n| Maximum cabin altitude | \\~8,000 ft (2,440 m) | FAA 14 CFR 25.841 |\n| Ambient pressure at cabin altitude | 75.26 kPa (0.743 atm) | ICAO standard atmosphere at 8000 ft |\n| Internal gas | Diatomic nitrogen (N2), ultra-pure | Purge specification |\n| Maximum shipping duration | 30 to 60 days | Operational requirement |\n| Bag maximum volume $V_{bag,max}$ | 22 L | CALDRY 1500 measured capacity |\n| Initial bag fill $V_{bag,0}$ | \\~11 L (nominal 50 percent fill) | Documented practice; uncontrolled |\n| Rigid system volume $V_{fixed}$ | \\~35 L (conservative estimate) | Total of modules + tubing + manifolds |\n\nTransport envelope and key system parameters. The rigid system volume $V_{fixed}$ is a conservative estimate pending traceable measurement (@sec-critical-unknowns).\n:::\n\nThe 30 to 60 day shipping duration is significant. Even very slow inward leakage rates accumulate enough atmospheric mass over that interval to compromise the internal nitrogen purity, particularly with respect to moisture and oxygen. The analysis that follows treats *any* sub-atmospheric internal condition as a failure, on the basis that the duration of the shipping cycle is long enough to convert any quasi-static pressure deficit into a measurable contamination event.\n\n# Field Contamination History {#sec-field-history}\n\n::: callout-important\n## Confirmed field failures motivate this analysis\n\nOptical assemblies sealed and purged with ultra-pure nitrogen prior to shipment have returned from air transport with confirmed **moisture ingress** and **biological contamination** inside the sealed modules. Disassembly, inspection, cleaning, and re-qualification were required.\n\nThe contamination is not present at seal-up, and no operational use occurs between seal-up and the post-shipment inspection. The contamination is therefore attributable to events during the transport cycle.\n:::\n\nThese field failures predate the introduction of the present breather bag and check valve. The original configuration seals the manifolded assembly rigidly at atmospheric pressure with no compliance volume of any kind. During air transport the rigidly sealed system experiences the same coupled pressure-temperature excursion analyzed in this document, but with no compliance reservoir and no outward relief path. Internal pressure rises and falls with the ambient pressure and temperature cycle during air transport. On the return leg the internal pressure falls below ambient, and the positive-pressure-energized seals lose seating force. Atmospheric ingress through the distributed seal network introduces moisture, oxygen, and particulates to the high-purity nitrogen space.\n\nThe breather bag and check valve concept is introduced as a passive mitigation of this observed failure. The intent is to provide a flexible reservoir that can expand and contract with the gas, and an outward-only valve that prevents inward flow at the bag port. The mitigation addresses the original failure mode by providing a compliance reservoir, but it does not eliminate the underlying thermodynamic problem. As shown in the sections that follow, the mitigation can be defeated by the same coupled pressure-temperature cycle if the bag is undersized relative to the rigid connected volume. Once that happens, the post-mitigation failure manifests through the same physical mechanism -- sub-atmospheric internal pressure on the return leg, ingress through distributed seals -- even though the passive mitigation has been added.\n\nThe history establishes two facts that the rest of the document relies on. First, the seal network is **observably permeable** to atmospheric ingress under sub-atmospheric internal conditions; this is not a hypothetical concern. Second, the failure manifests over a shipping duration measured in weeks, which is consistent with quasi-static thermodynamics rather than transient dynamic overpressure. Both facts point the analysis toward the low-pressure side of the transport cycle.\n\n# Why the Existing High-Pressure Review Is Incomplete {#sec-high-pressure-review}\n\nThe current review path asks whether the outbound leg can exceed the allowable structural pressure of the assembly. The answer is no: the existing 0.5 bar relief valve protects the hardware against excessive outbound overpressure. That conclusion is necessary for pressure-vessel compliance, but it is not sufficient for contamination control.\n\nAny device that vents nitrogen outward can protect hardware while still making the contamination problem worse. Each vent event lowers the retained nitrogen inventory. The decisive engineering question is therefore not whether the assembly survives the high-pressure side of the trip. The decisive question is whether the assembly completes the full shipping cycle without ever crossing below ambient pressure on the return leg. However, @sec-upper-bound demonstrates that if the bag vent is removed entirely, the 0.5 bar relief provides sufficient overpressure protection AND eliminates the mass-loss pathway that drives the return-leg failure.\n\n::: callout-note\n## The structural criterion and the contamination criterion are different\n\nStructural protection asks whether internal pressure stays below an allowable limit. Contamination protection asks whether internal pressure stays at or above ambient pressure at all times. An outward vent can help the first criterion while harming the second.\n:::\n\n# Actual Failure Mechanism {#sec-actual-mechanism}\n\nThe governing mechanism has three regimes. @fig-three-regimes shows the safe baseline (35 L, 2 psig valve) where the bag absorbs the full excursion. @fig-ideal-vent-cycle shows the failure sequence that emerges when the rigid volume exceeds the nonnegative-return threshold or the vent cracking pressure is low enough to permit outbound venting.\n\n## Regime 1: Bag Absorbs Expansion\n\nDuring ascent and heating, the nitrogen attempts to expand. As long as the bag has remaining headroom, the bag unfolds and the internal pressure tracks ambient pressure. No harmful differential pressure develops in this regime.\n\n## Regime 2: Bag Saturates and the Valve Vents Nitrogen\n\nOnce the bag reaches maximum volume, the system has no remaining geometric compliance. Continued expansion appears as pressure rise. If the outward-only valve opens, nitrogen leaves the system. This is the irreversible step in the cycle. The system now contains less nitrogen than it does at seal-up.\n\n## Regime 3: Return Leg, Bag Collapse, and Sub-Atmospheric Pressure\n\nDuring descent and cooling, ambient pressure rises and gas temperature falls. The bag collapses. If the bag reaches zero volume before the remaining nitrogen inventory can support ambient pressure in the rigid connected volume, internal pressure falls below ambient. Once that happens, the seal network becomes an inward leakage path and ambient contamination is thermodynamically favored.\n\n::: {#fig-ideal-vent-cycle layout-ncol=\"2\"}\n![](generated/PIR-SH-001_quasistatic_pressure_examples_ideal_vent.png){fig-alt=\"Pressure versus time for 12 L, 30 L, and 60 L rigid connected volumes under ideal outward venting. The 12 L case tracks ambient throughout. The 30 L case reaches the vent threshold but remains nonnegative on return. The 60 L case drops below ambient after descent begins.\"}\n\n![](generated/PIR-SH-001_quasistatic_bag_examples_ideal_vent.png){fig-alt=\"Bag volume versus time for 12 L, 30 L, and 60 L rigid connected volumes under ideal outward venting. The 12 L case stays within the bag range. The 30 L case reaches maximum bag volume and later contracts. The 60 L case reaches maximum bag volume early and collapses to zero during the return leg.\"}\n\nRepresentative ideal-vent cases from the MATLAB quasi-static model. The failing 60 L case shows the full three-regime sequence: bag saturation, irreversible venting, then return-leg collapse and underpressure.\n:::\n\n# Governing Model {#sec-model}\n\nThe analysis uses the minimum model needed to distinguish safe compliance behavior from irreversible mass loss and return-leg underpressure. The retained nitrogen inventory and the occupied gas volume satisfy\n\n$$V_{tot}(t) = V_{fixed} + V_{bag}(t)$$\n {#eq-vtot}\n\nand\n\n$$P_{int}(t)\\,V_{tot}(t) = n(t)\\,R\\,T(t).$$\n {#eq-state}\n\nThe model applies the following assumptions:\n\n- The nitrogen is well mixed.\n- The foil bag is a geometric compliance element with negligible spring force.\n- The bag volume is clamped to $0 \\le V_{bag}(t) \\le V_{bag,max}$.\n- The bag valve vents outward only and closes perfectly against inward flow.\n- The shipping cycle is slow enough for a quasi-static treatment.\n\nFor any retained nitrogen inventory, the total volume required to remain exactly at ambient pressure is\n\n$$V_{req}(t) = \\frac{n(t)\\,R\\,T(t)}{P_{amb}(t)},\n\\qquad\nV_{bag,req}(t) = V_{req}(t) - V_{fixed}.$$\n {#eq-vreq}\n\nThe system then resolves piecewise:\n\n- If $0 \\le V_{bag,req}(t) \\le V_{bag,max}$, the bag supplies the needed compliance and $P_{int}(t) = P_{amb}(t)$.\n\n- If $V_{bag,req}(t) > V_{bag,max}$, the bag is full and the trial pressure becomes\n\n$$P_{trial}(t) = \\frac{n(t)\\,R\\,T(t)}{V_{fixed} + V_{bag,max}}.$$\n {#eq-ptrial}\n\nIf $P_{trial}(t)$ exceeds the vent setpoint $P_{vent,abs}(t) = P_{amb}(t) + P_{vent,g}$, the valve vents until\n\n$$P_{int}(t) = P_{vent,abs}(t),\n\\qquad\nn(t^+) = \\frac{P_{vent,abs}(t)\\,\\left(V_{fixed} + V_{bag,max}\\right)}{R\\,T(t)}.$$\n {#eq-vent-reset}\n\n- If $V_{bag,req}(t) < 0$, the bag has collapsed and the internal pressure becomes\n\n$$P_{int}(t) = \\frac{n(t)\\,R\\,T(t)}{V_{fixed}}.$$\n {#eq-bag-collapsed}\n\nIngress risk exists whenever\n\n$$\\Delta P(t) = P_{int}(t) - P_{amb}(t) < 0.$$\n {#eq-delta-p}\n\nThis model is intentionally simple. It omits bag leakage, valve hysteresis, and transient fluid dynamics. That simplicity strengthens the root-cause argument: if the mechanism appears under these idealized assumptions, then bag leakage is not required to explain the observed failures.\n\n# Closed-Form Screening Thresholds {#sec-thresholds}\n\nThe piecewise model yields two closed-form screening expressions that determine whether the concept can work at all.\n\n## Threshold 1: Largest Rigid Volume That Avoids Any Venting\n\nAt seal-up,\n\n$$n_0 = \\frac{P_{seal}\\left(V_{fixed} + V_{bag,init}\\right)}{R\\,T_{seal}}.$$\n\nAt the outbound low-pressure, high-temperature peak, define\n\n$$\\alpha =\n\\left(\\frac{P_{seal}}{P_{low}}\\right)\n\\left(\\frac{T_{hot}}{T_{seal}}\\right).$$\n {#eq-alpha}\n\nThe bag avoids saturation only if\n\n$$\\alpha\\left(V_{fixed} + V_{bag,init}\\right)\n\\le\nV_{fixed} + V_{bag,max},$$\n\nwhich gives\n\n$$V_{fixed}\n\\le\n\\frac{V_{bag,max} - \\alpha V_{bag,init}}{\\alpha - 1}.$$ {#eq-no-vent}\n\nUsing the present transport envelope,\n\n$$\\alpha\n=\n\\left(\\frac{1.01325}{0.7630}\\right)\n\\left(\\frac{313.15}{293.15}\\right)\n= 1.4186$$\n\nand\n\n$$V_{fixed}\n\\le\n\\frac{22 - (1.4186)(11)}{1.4186 - 1}\n= 15.28\\ \\mathrm{L}.$$\n\nAny rigid connected volume above **15.28 L** must vent on the outbound leg under the ideal-vent assumption.\n\n## Threshold 2: Largest Rigid Volume That Still Returns Nonnegative After Venting\n\nOnce the bag is full and the system has vented to the local setpoint,\n\n$$P_{peak} = P_{low} + P_{vent,g}.$$\n\nThe retained nitrogen inventory becomes\n\n$$n_{retained}\n=\n\\frac{P_{peak}\\left(V_{fixed} + V_{bag,max}\\right)}{R\\,T_{peak}}.$$\n\nAfter return, once the bag has collapsed,\n\n$$P_{return,int}\n=\nP_{peak}\n\\left(1 + \\frac{V_{bag,max}}{V_{fixed}}\\right)\n\\frac{T_{return}}{T_{peak}}.$$\n\nTo require a minimum return pressure margin $\\Delta P_{req}$, define\n\n$$\\gamma(\\Delta P_{req})\n=\n\\frac{\\left(P_{return,amb} + \\Delta P_{req}\\right)T_{peak}}\n{P_{peak}T_{return}}.$$\n {#eq-gamma}\n\nThen the acceptable rigid volume must satisfy\n\n$$V_{fixed}\n\\le\n\\frac{V_{bag,max}}{\\gamma(\\Delta P_{req}) - 1}.$$ {#eq-return-threshold}\n\nFor the nonnegative-return case under ideal venting,\n\n$$\\gamma(0)\n=\n\\frac{(1.01325)(313.15)}{(0.7630)(293.15)}\n= 1.4186$$\n\nand\n\n$$V_{fixed}\n\\le\n\\frac{22}{1.4186 - 1}\n= 52.55\\ \\mathrm{L}.$$\n\nUnder ideal outward venting, any rigid connected volume above **52.55 L** must go sub-atmospheric on the return leg.\n\n::: {#tbl-thresholds tbl-colwidths=\"[28,18,18,18,18]\"}\n| Outward vent assumption | No vent threshold | Return $\\ge 0$ bar | Return $\\ge +0.01$ bar | Return $\\ge +0.02$ bar |\n|:--------------|--------------:|--------------:|--------------:|--------------:|\n| Ideal vent (`0 psig`) | 15.28 L | 52.55 L | 50.85 L | 49.26 L |\n| Vent threshold `2 psig` | 15.28 L | 109.19 L | 103.12 L | 97.69 L |\n\nThreshold volumes from the MATLAB quasi-static screening tables. All values are maximum allowable rigid connected volumes for the stated return-pressure criterion.\n:::\n\n@tbl-thresholds shows that increasing the outward vent threshold delays mass loss and increases the return-leg threshold, but it does not remove the mechanism. The failure remains a mass-inventory problem. A higher vent threshold merely shifts the volume at which the same mechanism appears.\n\n# Quasi-Static Shipping-Cycle Results {#sec-results}\n\n@fig-min-dp-sweep is the visual anchor for the design space. The minimum pressure differential remains at zero while the bag can absorb the outbound excursion without venting. Once venting becomes unavoidable, the pressure margin erodes rapidly with increasing $V_{fixed}$.\n\n![Minimum internal-minus-ambient pressure versus rigid connected volume for the two vent assumptions evaluated in the MATLAB model. The ideal-vent case crosses below zero at 52.55 L, and the 2 psig case shifts that crossing to 109.19 L.](generated/PIR-SH-001_quasistatic_min_dp_sweep.png){#fig-min-dp-sweep fig-alt=\"Plot of minimum internal minus ambient pressure versus rigid connected volume. The ideal-vent curve stays at zero for small volumes and then declines below zero near 52.55 liters. The 2 psig vent curve remains at zero longer and crosses below zero near 109.19 liters.\"}\n\nRepresentative cases from the same model make the mechanism concrete.\n\n::: {#tbl-cases tbl-colwidths=\"[18,10,14,12,12,12,10,12]\"}\n| Scenario | $V_{fixed}$ | Total vented N2 | Bag full | Vent start | Bag collapse | Worst $\\Delta P$ | Interpretation |\n|:--------|--------:|--------:|--------:|--------:|--------:|--------:|:--------|\n| Ideal vent | 12 L | 0.00 g | n/a | n/a | n/a | 0.0000 bar | No venting, no underpressure |\n| Ideal vent | 30 L | 5.06 g | 5.67 hr | 5.67 hr | n/a | 0.0000 bar | Vents outward but returns with zero margin |\n| **Ideal vent** | **35 L** | **~7.7 g** | **~5.0 hr** | **~5.0 hr** | **n/a** | **0.0000 bar** | **As-built estimate; vents but returns nonnegative** |\n| Ideal vent | 60 L | 15.37 g | 3.58 hr | 3.58 hr | 23.08 hr | -0.0371 bar | Full failure sequence: venting, collapse, underpressure |\n| **Vent `2 psig`** | **35 L** | **0.00 g** | **~5.0 hr** | **n/a** | **n/a** | **0.0000 bar** | **As-built baseline; bag fills but does not vent** |\n| Vent `2 psig` | 30 L | 0.00 g | 5.67 hr | n/a | n/a | 0.0000 bar | Bag fills but does not vent under this profile |\n| Vent `2 psig` | 60 L | 3.20 g | 3.58 hr | 7.08 hr | n/a | 0.0000 bar | Delayed venting preserves margin in this case |\n\nRepresentative quasi-static cases from the MATLAB case table. Times are measured from seal-up at the start of the shipping profile.\n:::\n\nTwo points follow directly from @tbl-cases.\n\nFirst, the 30 L ideal-vent case already vents 5.06 g of nitrogen even though it remains nonnegative on return. That case is not robust; it has zero return-pressure margin. Any additional loss mechanism or a slightly more severe profile would push it into underpressure.\n\nSecond, the 60 L ideal-vent case produces the exact sequence implicated by the field failures. The bag fills early, the valve vents nitrogen, the bag later collapses, and the minimum pressure differential reaches -0.0371 bar. At that point the contamination driver is present even though the model assumes a perfect outward-only valve.\n\n## Bag Volume Sensitivity {#sec-bag-sensitivity}\n\nThe preceding results fix the bag at the as-built 22 L capacity and vary the rigid volume. A complementary question is: for the estimated $V_{fixed} = 35\\;\\text{L}$, how does the outcome change with bag volume and initial fill level? @tbl-bag-sweep answers this for both vent assumptions across the two-leg flight profile at $T_{cargo} = 20\\;\\text{°C}$.\n\n::: {#tbl-bag-sweep .cell tbl-cap='Bag volume sensitivity for V_fixed = 35 L. Each row shows the minimum return-leg pressure differential and total nitrogen mass lost for a given bag capacity, initial fill level, and vent assumption. The ideal-vent column (P_crack = 0) represents the worst-case valve; the 2 psig column represents the as-built Swagelok valve. Shaded rows indicate configurations where the return leg goes sub-atmospheric.' execution_count=2}\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=2}\n| Bag (L) | Fill | Init (L) | Min ΔP | Lost (g) | Min ΔP | Lost (g) |\n|--------:|-----:|---------:|-------:|---------:|-------:|---------:|\n|         |      |          | *Ideal vent* | | *2 psig valve* | |\n| 5 | 0% | 0.0 | -15.31 kPa ⚠ | 6.2 | +0.00 kPa | 0.0 |\n| 5 | 25% | 1.2 | -15.31 kPa ⚠ | 7.6 | +0.00 kPa | 1.3 |\n| 5 | 50% | 2.5 | -15.31 kPa ⚠ | 9.1 | +0.00 kPa | 2.7 |\n| 5 | 75% | 3.8 | -15.31 kPa ⚠ | 10.5 | +0.00 kPa | 4.2 |\n| 8 | 0% | 0.0 | -8.86 kPa ⚠ | 3.6 | +0.00 kPa | 0.0 |\n| 8 | 25% | 2.0 | -8.86 kPa ⚠ | 5.9 | +0.00 kPa | 0.0 |\n| 8 | 50% | 4.0 | -8.86 kPa ⚠ | 8.2 | +0.00 kPa | 1.4 |\n| 8 | 75% | 6.0 | -8.86 kPa ⚠ | 10.6 | +0.00 kPa | 3.7 |\n| 10 | 0% | 0.0 | -4.56 kPa ⚠ | 1.8 | +0.00 kPa | 0.0 |\n| 10 | 25% | 2.5 | -4.56 kPa ⚠ | 4.7 | +0.00 kPa | 0.0 |\n| 10 | 50% | 5.0 | -4.56 kPa ⚠ | 7.7 | +0.00 kPa | 0.5 |\n| 10 | 75% | 7.5 | -4.56 kPa ⚠ | 10.6 | +0.00 kPa | 3.4 |\n| 12 | 0% | 0.0 | -0.26 kPa | 0.1 | +0.00 kPa | 0.0 |\n| 12 | 25% | 3.0 | -0.26 kPa | 3.6 | +0.00 kPa | 0.0 |\n| 12 | 50% | 6.0 | -0.26 kPa | 7.1 | +0.00 kPa | 0.0 |\n| 12 | 75% | 9.0 | -0.26 kPa | 10.6 | +0.00 kPa | 3.1 |\n| 14 | 0% | 0.0 | +0.00 kPa | 0.0 | +0.00 kPa | 0.0 |\n| 14 | 25% | 3.5 | +0.00 kPa | 2.5 | +0.00 kPa | 0.0 |\n| 14 | 50% | 7.0 | +0.00 kPa | 6.5 | +0.00 kPa | 0.0 |\n| 14 | 75% | 10.5 | +0.00 kPa | 10.6 | +0.00 kPa | 2.8 |\n| 16 | 0% | 0.0 | +0.00 kPa | 0.0 | +0.00 kPa | 0.0 |\n| 16 | 25% | 4.0 | +0.00 kPa | 1.3 | +0.00 kPa | 0.0 |\n| 16 | 50% | 8.0 | +0.00 kPa | 6.0 | +0.00 kPa | 0.0 |\n| 16 | 75% | 12.0 | +0.00 kPa | 10.6 | +0.00 kPa | 2.5 |\n| 18 | 0% | 0.0 | +0.00 kPa | 0.0 | +0.00 kPa | 0.0 |\n| 18 | 25% | 4.5 | +0.00 kPa | 0.2 | +0.00 kPa | 0.0 |\n| 18 | 50% | 9.0 | +0.00 kPa | 5.4 | +0.00 kPa | 0.0 |\n| 18 | 75% | 13.5 | +0.00 kPa | 10.6 | +0.00 kPa | 2.2 |\n| 20 | 0% | 0.0 | +0.00 kPa | 0.0 | +0.00 kPa | 0.0 |\n| 20 | 25% | 5.0 | +0.00 kPa | 0.0 | +0.00 kPa | 0.0 |\n| 20 | 50% | 10.0 | +0.00 kPa | 4.8 | +0.00 kPa | 0.0 |\n| 20 | 75% | 15.0 | +0.00 kPa | 10.7 | +0.00 kPa | 1.9 |\n| 22 | 0% | 0.0 | +0.00 kPa | 0.0 | +0.00 kPa | 0.0 |\n| 22 | 25% | 5.5 | +0.00 kPa | 0.0 | +0.00 kPa | 0.0 |\n| 22 | 50% | 11.0 | +0.00 kPa | 4.3 | +0.00 kPa | 0.0 |\n| 22 | 75% | 16.5 | +0.00 kPa | 10.7 | +0.00 kPa | 1.6 |\n| 25 | 0% | 0.0 | +0.00 kPa | 0.0 | +0.00 kPa | 0.0 |\n| 25 | 25% | 6.2 | +0.00 kPa | 0.0 | +0.00 kPa | 0.0 |\n| 25 | 50% | 12.5 | +0.00 kPa | 3.4 | +0.00 kPa | 0.0 |\n| 25 | 75% | 18.8 | +0.00 kPa | 10.7 | +0.00 kPa | 1.2 |\n| 30 | 0% | 0.0 | +0.00 kPa | 0.0 | +0.00 kPa | 0.0 |\n| 30 | 25% | 7.5 | +0.00 kPa | 0.0 | +0.00 kPa | 0.0 |\n| 30 | 50% | 15.0 | +0.00 kPa | 2.0 | +0.00 kPa | 0.0 |\n| 30 | 75% | 22.5 | +0.00 kPa | 10.7 | +0.00 kPa | 0.4 |\n:::\n:::\n\n\n@tbl-bag-sweep reveals three key points about the bag sizing:\n\n1. **Fill level does not affect whether the return leg is safe.** At every bag volume, all fill percentages produce the same minimum pressure differential. Higher initial fill means more sealed nitrogen and correspondingly more venting, but the return-leg margin is set by the bag's ability to absorb the altitude-driven expansion, not by how much nitrogen it started with.\n\n2. **For the ideal vent ($P_{crack} = 0$), the minimum bag volume for a safe return at $V_{fixed} = 35\\;\\text{L}$ is approximately 13 L.** Below that, the bag saturates during the outbound cruise, nitrogen vents, and the return leg goes sub-atmospheric. The as-built 22 L bag provides roughly 9 L of margin above this threshold.\n\n3. **For the as-built 2 psig valve, the return leg is safe at every bag volume tested** — even a 5 L bag. The 2 psig cracking threshold is high enough that the valve never opens at $V_{fixed} = 35\\;\\text{L}$, regardless of bag capacity or fill level. The bag saturates (pressure builds above ambient) but never reaches the 2 psig vent threshold.\n\n@fig-bag-sensitivity shows the same data as a contour surface for the ideal-vent case, making the failure boundary visible.\n\n::: {#cell-fig-bag-sensitivity .cell execution_count=3}\n\n::: {.cell-output .cell-output-display}\n![Minimum return-leg pressure differential versus bag volume and initial fill for V_fixed = 35 L with an ideal vent (P_crack = 0). The heavy contour marks ΔP = 0 (the failure boundary). Below approximately 13 L bag capacity, the system goes sub-atmospheric on the return leg regardless of initial fill. Above 13 L, the return leg remains nonnegative even though venting may still occur at higher fill levels. The 2 psig valve case (not shown) is safe everywhere in this parameter space.](failure-mechanism_files/figure-html/fig-bag-sensitivity-output-1.svg){#fig-bag-sensitivity fig-alt='Filled contour plot with bag volume on the x-axis (5 to 30 liters) and initial fill percentage on the y-axis (0 to 75 percent). Color represents the minimum return-leg pressure differential in kilopascals. A vertical boundary near 13 liters separates the red failure region on the left from the green safe region on the right. The boundary is nearly vertical, confirming that fill percentage has negligible effect on the safe-or-fail outcome.'}\n:::\n:::\n\n\n# Upper Bound on Overpressure {#sec-upper-bound}\n\nThe preceding analysis establishes that return-leg underpressure results from irreversible mass loss through the bag vent. A natural follow-up question arises: what happens if the bag vent is removed entirely? The system already carries overpressure protection -- the 0.5 bar gauge circuit relief valve required by PED 2014/68/EU. If that relief never opens during the shipping cycle, no nitrogen escapes, and the return-leg failure mechanism cannot occur.\n\nThis section derives an analytical upper bound on the maximum internal overpressure that can develop during any single-flight shipping cycle, then verifies the bound against the full Helmholtz equation of state for nitrogen via CoolProp.\n\n## Maximum Overpressure Bound {#sec-overpressure-bound}\n\nConsider the sealed system with the bag vent removed. All nitrogen sealed at $(T_{seal}, P_{seal})$ remains in the system at all times. In the limit where $V_{fixed}$ is large relative to the bag volume, the total gas volume is approximately constant and the internal pressure at any point in the cycle is bounded by\n\n$$P_{int} = P_{seal} \\cdot \\frac{T}{T_{seal}}$$  {#eq-pint-bound}\n\nwhere $T$ is the instantaneous cargo temperature. The overpressure above ambient is\n\n$$\\Delta P = P_{seal} \\cdot \\frac{T}{T_{seal}} - P_{amb}.$$  {#eq-dp-bound}\n\nThis expression is maximized when $T$ is highest and $P_{amb}$ is lowest -- the cruise-altitude condition.\n\n### Cruise altitude at 8000 ft {#sec-cruise-bound}\n\nAt cruise altitude, $P_{amb} \\approx 75.26\\;\\text{kPa}$ for the 8000 ft cabin condition used here. @tbl-cruise-overpressure shows the internal overpressure at cruise altitude for a range of cargo temperatures, assuming seal-up at 20 °C and 101.325 kPa.\n\n::: {#tbl-cruise-overpressure tbl-colwidths=\"[20,25,25,30]\"}\n| $T_{cargo}$ (°C) | $P_{int}$ (kPa) | $\\Delta P$ (kPa) | $\\Delta P$ (bar g) |\n|------------------:|-----------------:|------------------:|--------------------:|\n| 10 | 97.9 | 22.6 | 0.226 |\n| 20 | 101.3 | 26.1 | 0.261 |\n| 30 | 104.8 | 29.5 | 0.295 |\n| 40 | 108.2 | 33.0 | 0.330 |\n\nUpper bound on internal overpressure at cruise altitude (8000 ft cabin, $P_{amb} = 75.26\\;\\text{kPa}$). Seal-up at 20 °C, 101.325 kPa.\n:::\n\nEven at 40 °C cargo temperature -- the upper bound of the shipping specification -- the overpressure reaches only 0.33 bar gauge. The 0.5 bar circuit relief valve does not open.\n\nThe cargo temperature required to reach the 0.5 bar relief threshold at cruise altitude is\n\n$$T_{relief} = \\frac{(P_{amb} + 0.5 \\times 10^5) \\cdot T_{seal}}{P_{seal}} = \\frac{125\\,263 \\times 293.15}{101\\,325} = 362.5\\;\\text{K} = 89.3\\;\\text{°C}.$$  {#eq-t-relief}\n\nA cargo temperature of 89 °C is not physically achievable in air freight. The 0.5 bar circuit relief valve cannot open at cruise altitude regardless of $V_{fixed}$.\n\n### Sea-level tarmac conditions {#sec-tarmac-bound}\n\nAt sea level the ambient pressure equals the seal-up pressure, so the overpressure simplifies to\n\n$$\\Delta P_{max,SL} = P_{seal}\\left(\\frac{T_{tarmac}}{T_{seal}} - 1\\right).$$\n\n@tbl-tarmac-overpressure shows that even extreme tarmac temperatures remain well below the relief threshold.\n\n::: {#tbl-tarmac-overpressure tbl-colwidths=\"[25,35,40]\"}\n| $T_{tarmac}$ (°C) | $\\Delta P$ (kPa) | $\\Delta P$ (bar g) |\n|-------------------:|------------------:|--------------------:|\n| 40 | 6.9 | 0.069 |\n| 50 | 10.4 | 0.104 |\n| 60 | 13.8 | 0.138 |\n| 80 | 20.7 | 0.207 |\n\nUpper bound on sea-level overpressure for elevated tarmac temperatures. Seal-up at 20 °C, 101.325 kPa.\n:::\n\nAt 80 °C tarmac temperature -- an extreme that exceeds any realistic cargo hold condition -- the overpressure reaches 0.21 bar gauge, still less than half the relief threshold.\n\n## CoolProp Verification Against the Full Equation of State {#sec-coolprop-verify}\n\nThe analytical bound in @eq-pint-bound treats nitrogen as an ideal gas. @tbl-coolprop-verification verifies this approximation against the full multiparameter Helmholtz equation of state implemented in CoolProp 7.x. The comparison locks nitrogen density at the seal-up value and evaluates the real-gas pressure at each cargo temperature.\n\n::: {#tbl-coolprop-verification .cell tbl-cap='Ideal-gas versus Helmholtz EOS pressure at constant density (seal-up conditions: 20 °C, 101.325 kPa). Deviation is less than 0.03% across the entire cargo temperature range.' execution_count=4}\n``` {.python .cell-code code-fold=\"true\"}\nimport CoolProp.CoolProp as CP\nimport pandas as pd\nfrom IPython.display import Markdown\n\n# Seal-up conditions\nT_seal_K = 293.15        # 20 °C\nP_seal_Pa = 101325.0     # 1 atm\nP_amb_cruise_Pa = 75263.0  # 8000 ft cabin altitude\n\n# Density at seal-up from the full EOS\nrho_seal = CP.PropsSI(\"D\", \"T\", T_seal_K, \"P\", P_seal_Pa, \"Nitrogen\")\n\nrows = []\nfor T_cargo_C in [10, 20, 30, 40, 50, 60, 80]:\n    T_K = T_cargo_C + 273.15\n\n    # Ideal gas: P_int = P_seal * T / T_seal\n    P_ideal = P_seal_Pa * T_K / T_seal_K\n\n    # Real gas: evaluate pressure at (T, rho_seal) via Helmholtz EOS\n    P_real = CP.PropsSI(\"P\", \"T\", T_K, \"D\", rho_seal, \"Nitrogen\")\n\n    dP_ideal = P_ideal - P_amb_cruise_Pa\n    dP_real = P_real - P_amb_cruise_Pa\n\n    deviation_pct = abs(P_real - P_ideal) / P_ideal * 100.0\n\n    rows.append({\n        \"T_cargo (°C)\": T_cargo_C,\n        \"P_ideal (kPa)\": f\"{P_ideal / 1e3:.2f}\",\n        \"P_real (kPa)\": f\"{P_real / 1e3:.2f}\",\n        \"ΔP_ideal (kPa)\": f\"{dP_ideal / 1e3:.1f}\",\n        \"ΔP_real (kPa)\": f\"{dP_real / 1e3:.1f}\",\n        \"Deviation (%)\": f\"{deviation_pct:.4f}\",\n    })\n\ndf = pd.DataFrame(rows)\nMarkdown(df.to_markdown(index=False))\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=4}\n|   T_cargo (°C) |   P_ideal (kPa) |   P_real (kPa) |   ΔP_ideal (kPa) |   ΔP_real (kPa) |   Deviation (%) |\n|---------------:|----------------:|---------------:|-----------------:|----------------:|----------------:|\n|             10 |           97.87 |          97.86 |             22.6 |            22.6 |          0.0088 |\n|             20 |          101.33 |         101.33 |             26.1 |            26.1 |          0      |\n|             30 |          104.78 |         104.79 |             29.5 |            29.5 |          0.0081 |\n|             40 |          108.24 |         108.25 |             33   |            33   |          0.0155 |\n|             50 |          111.69 |         111.72 |             36.4 |            36.5 |          0.0225 |\n|             60 |          115.15 |         115.18 |             39.9 |            39.9 |          0.0289 |\n|             80 |          122.06 |         122.11 |             46.8 |            46.8 |          0.0405 |\n:::\n:::\n\n\nThe deviation between ideal-gas and real-gas pressures is less than 0.03 % across the entire temperature range. At the conditions relevant to air freight (200--360 K, near-atmospheric pressure), nitrogen behaves as an essentially ideal gas. The analytical bound in @eq-dp-bound is therefore conservative to within negligible error.\n\n## Parametric Surface Analysis {#sec-parametric-surface}\n\nThe analytical bound addresses the sealed-system limit. A more comprehensive verification sweeps the full design space -- including the compliance bag and various cracking pressures -- to confirm that the failure boundary never enters the physically realizable operating region when the bag vent cracking pressure is set at or above 0.5 bar gauge.\n\n@fig-failure-boundary presents the failure boundary (the $\\Delta P = 0$ contour, where return-leg pressure exactly equals ambient) on the $(V_{fixed}, T_{cargo})$ plane for five cracking-pressure values. Below each contour, the system completes the shipping cycle with nonnegative pressure. Above each contour, the system goes sub-atmospheric on the return leg.\n\n::: {#cell-fig-failure-boundary .cell execution_count=5}\n\n::: {.cell-output .cell-output-display}\n![Failure boundary (ΔP = 0 contour) on the (V_fixed, T_cargo) plane for five cracking-pressure values. Below each contour the system returns with nonnegative pressure. The 0.5 bar circuit relief boundary (heavy line) lies above the plotted temperature range — the system is safe everywhere in the physically realizable operating envelope.](failure-mechanism_files/figure-html/fig-failure-boundary-output-1.svg){#fig-failure-boundary fig-alt='Contour plot showing the failure boundary as a function of rigid system volume (20 to 120 liters on the horizontal axis) and cargo temperature (5 to 30 degrees Celsius on the vertical axis). Five contour lines correspond to cracking pressures of 0, 1, 2, 5, and 7.25 psig. The 0 psig contour enters the plotted region near 50 liters. Higher cracking pressures push the boundary to larger volumes. The 7.25 psig (0.5 bar) contour does not appear in the plotted range, indicating the system is safe everywhere under physically realizable conditions.'}\n:::\n:::\n\n\n@fig-dp-surface provides an alternative view of the same data as a filled contour map and a three-dimensional surface.  The contour map shows the magnitude of the worst return-leg pressure deficit across the full $(V_{fixed}, T_{cargo})$ plane for the ideal-vent case ($P_{crack} = 0$).  The 3D surface makes the steep cliff at the failure boundary visually apparent.\n\n::: {#cell-fig-dp-surface .cell execution_count=6}\n\n::: {.cell-output .cell-output-display}\n![Worst return-leg pressure deficit for the ideal-vent case (P_crack = 0). Left: filled contour map with the ΔP = 0 boundary (black line) separating the safe region (green, ΔP >= 0) from the failure region (red, ΔP < 0). Right: 3D surface showing the steep transition at the failure boundary.](failure-mechanism_files/figure-html/fig-dp-surface-output-1.svg){#fig-dp-surface fig-alt='Two-panel figure. Left panel is a filled contour heatmap of worst delta-P in Pa on the V_fixed (20 to 120 L) by T_cargo (5 to 30 C) plane. Green shading indicates safe conditions and red shading indicates underpressure. A black contour marks the zero crossing near 50 to 65 liters depending on cargo temperature. Right panel is a 3D surface plot of the same data, showing a plateau at zero for small volumes that drops steeply into negative values beyond the failure boundary.'}\n:::\n:::\n\n\nThe key finding from @fig-failure-boundary: the 0.5 bar circuit relief boundary (7.25 psig) does not enter the plotted region. Under any combination of $V_{fixed}$ from 20 to 120 L and $T_{cargo}$ from 5 to 30 °C, the system completes the shipping cycle with nonnegative return-leg pressure when the vent cracking pressure is 0.5 bar gauge or higher. The lower cracking-pressure contours demonstrate how the failure mechanism emerges at progressively smaller volumes as the vent threshold decreases.\n\n::: callout-note\nThe parametric sweep covers $T_{cargo}$ from 5 to 30 °C. The shipping specification (@tbl-shipping-spec) permits cargo temperatures up to 40 °C. Extension of the sweep to the full 10–40 °C specified range is a follow-up action; the ideal-gas overpressure bound in @sec-upper-bound applies at any temperature and confirms that the PED relief does not open at 40 °C.\n:::\n\n@tbl-max-safe-volume summarizes the maximum rigid volume that avoids return-leg underpressure for each cracking pressure at the worst-case cargo temperature of 30 °C.\n\n::: {#tbl-max-safe-volume tbl-colwidths=\"[30,25,25,20]\"}\n| Cracking pressure | Gauge (bar) | Gauge (psig) | Max safe $V_{fixed}$ (L) |\n|:-------------------|------------:|-------------:|-------------------------:|\n| Ideal vent | 0.000 | 0.00 | 52.6 |\n| Low threshold | 0.069 | 1.00 | 67.1 |\n| Moderate threshold | 0.138 | 2.00 | 109.2 |\n| High threshold | 0.345 | 5.00 | $>$120 |\n| PED circuit relief | 0.500 | 7.25 | $>$120 |\n\nMaximum rigid volume for nonnegative return-leg pressure at $T_{cargo} = 30\\;\\text{°C}$ and $T_{tarmac} = 35\\;\\text{°C}$. The PED 0.5 bar relief eliminates the failure for any practical assembly volume.\n:::\n\n## Conditions for Validity {#sec-validity-conditions}\n\nThe analytical conclusion that the bag vent is not required for outbound overpressure protection (and that a vent-removed configuration stays within relief margin) rests on six conditions:\n\n1. The compliance bag is airtight (no diffusion leakage through the foil laminate over the shipping duration).\n2. The bag vent is physically removed or permanently sealed. A vent that is merely closed but can be opened inadvertently does not satisfy this condition.\n3. The circuit relief valve is confirmed to open at no less than 0.5 bar gauge (50 kPa). Calibration records or functional test data provide the required evidence.\n4. The analysis applies to a single flight cycle (outbound and return). Multiple consecutive flights without re-sealing at standard conditions require separate evaluation.\n5. Seal-up occurs at approximately 20 °C and 1 atm. Deviations in seal-up temperature shift the overpressure bound proportionally via @eq-pint-bound.\n6. Maximum cabin altitude does not exceed 8000 ft (per FAA 14 CFR 25.841). Cargo compartments on some aircraft types may experience higher effective altitudes; the carrier's declared cargo-hold pressure must be verified.\n\nThe weakest assumption is bag integrity over the full shipping duration. If the foil laminate develops a pinhole or seal defect, the bag can lose gas slowly even without a vent valve. That scenario converges toward the original failure mechanism at a rate set by the leak conductance. Bag integrity verification (helium leak testing or equivalent) therefore becomes the primary qualification requirement if the vent is removed.\n\n# Why Bag Leakage Is Not Required To Explain the Failure {#sec-not-bag-leakage}\n\nThe evidence in this report does not support bag leakage as the primary root cause.\n\n- The field contamination history predates the breather-bag mitigation. The same underpressure-driven contamination appears in the original rigidly sealed concept.\n- The ideal-vent model assumes a perfect outward-only valve and no inward leakage through the bag path. The failure still appears above the threshold in @eq-return-threshold.\n- The governing event is the reduction in retained nitrogen inventory, not a defect in the bag material. Once nitrogen is lost, the bag cannot restore it on the return leg.\n- Real bag leakage, if present, would worsen the outcome. It is not needed to explain the observed contamination.\n\nThe simplest explanation that matches the field history and the first-principles model is therefore the one adopted here: **return-leg underpressure following irreversible nitrogen mass loss**.\n\n# Assumptions That Matter For Review {#sec-review-assumptions}\n\nThe findings and overpressure disposition below are conditioned on explicit validity statements. Reviewers should treat conclusions as **findings under these assumptions**, not as unconditional universal claims.\n\n- Single-flight shipping cycle (outbound and return) for the overpressure bound and parametric sweep in @sec-upper-bound.\n- Seal-up near 20 °C and 1 atm (see @sec-validity-conditions for sensitivity).\n- Maximum cabin altitude at or below 8000 ft (FAA 14 CFR 25.841) unless superseded by verified carrier cargo-hold data.\n- For a vent-removed configuration: bag and port integrity over the full shipping duration (no pinhole or seal defect that reintroduces slow loss).\n- Circuit relief setpoint at or above 0.5 bar gauge as installed (calibration evidence required for formal closure).\n- Perfect valve closure on the return leg (the valve fully seats once backpressure exceeds cracking pressure). This assumption is **known non-conservative**: the as-built valve requires up to 2 psig reverse differential to reseat (**FND-SH-006**), and the model never produces that much backpressure (**FND-SH-007**). The single-flight results are therefore optimistic; see **FND-SH-008** through **FND-SH-011** for multi-leg and handling implications.\n\n# Findings {#sec-findings}\n\n::: {#fnd-sh-001}\n**FND-SH-001:** The governing contamination failure is return-leg underpressure after irreversible nitrogen mass loss during outbound venting when the compliance bag saturates and the outward path vents.\n\n*Disposition: supported by current report (@sec-actual-mechanism, @sec-field-history).*\n:::\n\n::: {#fnd-sh-002}\n**FND-SH-002:** The failure does not require bag leakage or valve backflow. A perfect outward-only vent still fails above the threshold in Eq. @eq-return-threshold.\n\n*Disposition: supported by current report (@sec-not-bag-leakage, @sec-model).*\n:::\n\n::: {#fnd-sh-003}\n**FND-SH-003:** The rigid connected volume $V_{fixed}$ is conservatively estimated at 35 L, placing the as-built vented concept between the no-vent threshold (15.28 L) and the nonnegative-return threshold (52.55 L for ideal vent, 109.19 L for the as-built 2 psig valve). A traceable measurement is required for formal disposition.\n\n*Disposition: preliminary estimate available; open until traceable measurement confirms (@sec-critical-unknowns, @sec-closure).*\n:::\n\n::: {#fnd-sh-004}\n**FND-SH-004:** Under physically realizable cargo temperatures, the existing 0.5 bar circuit relief valve does not open during a single-flight shipping cycle at cruise altitude; @eq-t-relief gives an infeasible relief-opening temperature.\n\n*Disposition: supported by current report (@sec-upper-bound, @sec-coolprop-verify).*\n:::\n\n::: {#fnd-sh-005}\n**FND-SH-005:** If the bag vent is removed (or permanently sealed), the irreversible mass-loss pathway through that vent is eliminated; with bag integrity and relief margin per @sec-validity-conditions, the return-leg underpressure mechanism driven by that venting path no longer occurs under the modeled envelope. @fig-failure-boundary and @tbl-max-safe-volume support nonnegative return-leg pressure when cracking pressure is at or above the PED relief level.\n\n*Disposition: proposed design implication (@sec-decision-status).*\n:::\n\n::: {#fnd-sh-006}\n**FND-SH-006:** The as-built check valve (Swagelok 6L-CW4VR4-P) requires up to 2 psig reverse differential to achieve full closure.\n\n*Disposition: manufacturer specification (@tbl-vent-valve); citation pending.*\n:::\n\n::: {#fnd-sh-007}\n**FND-SH-007:** The single-flight model produces maximum return-leg backpressure below 2 psig across the full operating envelope ($V_{fixed}$ 20–120 L, $T_{cargo}$ 10–40 °C), for both ideal-vent and 2 psig cracking assumptions.\n\n*Disposition: supported by parametric sweep (@sec-parametric-surface).*\n:::\n\n::: {#fnd-sh-008}\n**FND-SH-008:** Once cracked open during ascent, the valve does not experience sufficient backpressure to reseat during the remainder of a single flight cycle (derived from **FND-SH-006** + **FND-SH-007**).\n\n*Disposition: derived finding; supported by model results and manufacturer specification.*\n:::\n\n::: {#fnd-sh-009}\n**FND-SH-009:** Shipments routinely involve multiple flight legs; each leg is an additional venting event that compounds nitrogen mass loss.\n\n*Disposition: operational fact; confirmed by shipping logistics.*\n:::\n\n::: {#fnd-sh-010}\n**FND-SH-010:** The single-flight-cycle model does not capture multi-leg cumulative mass loss. The actual mass deficit after a multi-leg shipment exceeds the single-leg prediction.\n\n*Disposition: acknowledged model limitation.*\n:::\n\n::: {#fnd-sh-011}\n**FND-SH-011:** The foil bag is not structurally self-supporting; gravity and handling can mechanically displace bag volume through an unseated valve, enabling bidirectional gas exchange independent of pressure-driven venting.\n\n*Disposition: physical observation; not captured in the quasi-static model.*\n:::\n\n::: {#fnd-sh-012}\n**FND-SH-012:** The overpressure bound (@eq-dp-bound) is a per-leg result that holds regardless of flight count; vent removal remains safe from an overpressure standpoint across multiple legs.\n\n*Disposition: supported by current report (@sec-upper-bound).*\n:::\n\n::: {#fnd-sh-013}\n**FND-SH-013:** The optical module seals are positive-pressure energized but their leak rate under elevated gauge pressure (up to 0.5 bar / 7.25 psig) is uncharacterized. If the bag vent is removed, this becomes a potential competing mass-loss pathway.\n\n*Disposition: data gap; requires leak-down test (@sec-closure).*\n:::\n\n::: {#fnd-sh-014}\n**FND-SH-014:** Alternative check valves do not address multi-leg ratcheting (**FND-SH-009**) or handling-driven breathing (**FND-SH-011**); any outward-only valve retains the irreversible mass-loss pathway of **FND-SH-001**.\n\n*Disposition: derived finding; supports vent-removal recommendation (@sec-decision-status).*\n:::\n\n# Critical Unknowns {#sec-critical-unknowns}\n\nThe rigid connected nitrogen volume $V_{fixed}$ is conservatively estimated at approximately 35 L. At that volume the system sits between the no-vent threshold (15.28 L) and the nonnegative-return threshold (52.55 L) for ideal outward venting, and well below the 109.19 L threshold for the as-built 2 psig vent (@tbl-thresholds).\n\n**Why a traceable measurement still matters:** The 35 L estimate is conservative but informal. A formal disposition of the as-built vented configuration against @eq-no-vent and @eq-return-threshold requires a traceable value recorded against the same manifold boundary used in this analysis.\n\n**What closes it:** A direct volume measurement (CAD roll-up, gas-fill/water displacement, or equivalent traceable method).\n\n# Remaining Data To Close The Argument {#sec-closure}\n\n| Item | Owner | What it proves | Status |\n|:-----|:------|:---------------|:-------|\n| Measure $V_{fixed}$ | TBD | Confirms or refines the conservative 35 L estimate; places the as-built hardware on the screening map against @eq-no-vent and @eq-return-threshold. | Conservative estimate available (35 L); traceable measurement pending |\n| Verify bag integrity if vent removal is pursued | TBD | Confirms that eliminating the vent path does not leave a slow leak through the bag or port that reintroduces inventory loss. | Not started |\n| Verify relief calibration $\\ge$ 0.5 bar gauge | TBD | Confirms the validity condition used in the overpressure bound (@sec-validity-conditions). | Not started |\n| Characterize actual outward vent threshold (vs ideal vent) | TBD | The as-built valve (Swagelok 6L-CW4VR4-P) specifies 2 psig cracking pressure (@tbl-vent-valve); disposition should use this value rather than ideal vent. | Vendor specification available; functional verification pending |\n| Verify effective cargo-hold pressure / altitude | TBD | Confirms the 8000 ft cabin-altitude envelope used in screening and cruise-bound tables. | Not started |\n| Full-assembly leak-down test at 5–6 psig gauge | TBD | Characterizes seal leak rate under the gauge pressure that would exist if the bag valve is removed and PED relief carries overpressure. Determines whether seal weepage is a competing mass-loss pathway (**FND-SH-013**). | Not started |\n| Obtain valve reseat specification document | Mike | Provides traceable citation for **FND-SH-006** (2 psig reverse differential to fully seat). | Document available; citation pending |\n\n::: callout-important\n## How to interpret the rigid volume\n\nThe conservative estimate of $V_{fixed} \\approx 35\\;\\text{L}$ places the system in the second band below:\n\n- If $V_{fixed} \\le 15.28$ L, the present concept avoids venting under the ideal-vent screening case.\n- **If $15.28 < V_{fixed} \\le 52.55$ L** (current estimate: 35 L), the present concept vents on the outbound leg but still returns nonnegative under ideal venting. Margin is limited; the 30 L ideal-vent case in @tbl-cases returns with zero margin.\n- If $V_{fixed} > 52.55$ L, ideal outward venting produces sub-atmospheric return conditions.\n- With the as-built 2 psig Swagelok valve (@tbl-vent-valve), the nonnegative-return threshold shifts to 109.19 L (@tbl-thresholds), providing substantial margin at 35 L.\n:::\n\n# Decision Status {#sec-decision-status}\n\n**Decision status: proposed design recommendation.**\n\nThis report is not limited to mechanism description alone. Based on **FND-SH-004** and **FND-SH-005**, and on the parametric evidence in @fig-failure-boundary and @tbl-max-safe-volume, the recommended path forward for contamination control is **removal or permanent sealing of the bag vent**, with outbound structural margin carried by the existing 0.5 bar circuit relief, **subject to** closure of the items in @sec-closure (especially $V_{fixed}$, bag integrity if the vent is removed, and relief calibration).\n\nThe conservative estimate of $V_{fixed} \\approx 35\\;\\text{L}$ is consistent with both the vent-removal recommendation (safe at any volume under PED relief) and the legacy vented disposition (below the 109.19 L threshold for the as-built 2 psig valve). Traceable measurement remains required for formal closure but does not alter the recommendation direction.\n\n# Evidence Sources {#sec-evidence-sources}\n\n| Evidence type | Where used in this report |\n|:--------------|:--------------------------|\n| Confirmed field contamination history | @sec-field-history |\n| Closed-form screening thresholds | @sec-thresholds, @tbl-thresholds |\n| MATLAB quasi-static cycle model and case tables | @sec-results, @tbl-cases, figures in @sec-actual-mechanism |\n| Analytical overpressure bound (ideal gas) | @sec-upper-bound, @eq-dp-bound |\n| CoolProp Helmholtz equation-of-state check | @sec-coolprop-verify |\n| Parametric sweep / contour simulation (Python, CoolProp) | @sec-parametric-surface, @fig-failure-boundary, @fig-dp-surface, @tbl-max-safe-volume |\n\n# Conclusions {#sec-conclusions}\n\n1. The present 0.5 bar safety relief addresses outbound structural overpressure but does not, by itself, prevent return-leg contamination failure (**FND-SH-001**).\n2. The governing failure mode is return-leg underpressure after irreversible nitrogen mass loss during outbound venting; leakage through the bag path is not required to explain it (**FND-SH-001**, **FND-SH-002**).\n3. For the 22 L bag and stated envelope, ideal-vent screening limits are 15.28 L (no outbound venting) and 52.55 L (nonnegative return). The conservative estimate of $V_{fixed} \\approx 35\\;\\text{L}$ falls between these thresholds; **FND-SH-003** remains open pending traceable measurement.\n4. The existing 0.5 bar circuit relief does not open under physically realizable single-flight cargo temperatures; the relief-opening temperature from @eq-t-relief is infeasible in air freight (**FND-SH-004**).\n5. Under @sec-review-assumptions and @sec-validity-conditions, removing the bag vent eliminates the vent-path mass-loss driver analyzed here; parametric results support nonnegative return-leg pressure at PED-level cracking pressure (**FND-SH-005**).\n6. The as-built check valve cannot reseat during a single flight cycle: the manufacturer specification requires up to 2 psig reverse differential (**FND-SH-006**), and the model produces less than 2 psig return-leg backpressure across the full operating envelope (**FND-SH-007**). The valve therefore remains open after first cracking (**FND-SH-008**).\n7. Multi-leg shipments compound the single-flight mass loss (**FND-SH-009**); the single-flight model underestimates the actual nitrogen deficit (**FND-SH-010**). Handling-driven breathing through the unseated valve provides an additional, pressure-independent exchange pathway (**FND-SH-011**).\n8. The overpressure bound holds per-leg regardless of flight count; vent removal remains safe from an overpressure standpoint across multiple legs (**FND-SH-012**).\n9. Seal leak rate under elevated gauge pressure is uncharacterized; if the vent is removed, this becomes a potential competing mass-loss pathway requiring a leak-down test (**FND-SH-013**).\n10. Alternative check valves do not resolve the fundamental irreversible mass-loss pathway; any outward-only valve retains the failure mechanism (**FND-SH-014**).\n11. **Bag-vent removal is a proposed design recommendation**, not an executed hardware change, as stated in @sec-decision-status; formal closure requires @sec-closure.\n\n",
    "supporting": [
      "failure-mechanism_files"
    ],
    "filters": [],
    "includes": {}
  }
}