{
  "hash": "a6d19c156fc7ab8ff28b0697a64efb57",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"25-Cycle Validation Test Plan -- ¼-80 Adjuster Galling Study\"\nauthor: \"Opto-Mechanical Engineering Group\"\ndate: 2025-05-22\nabstract: |\n  This test campaign ranks five material pairings for ¼-80 UN adjusters used in optics-grade mechanisms that must run dry in N₂ at 26 °C. The study captures friction torque, galling severity, particle generation, outgassing, resolution, and drift over 1×10⁶ cycles, producing a down-selection matrix and a calibrated friction-torque model.\nkeywords:\n  - validation testing\n  - galling resistance\n  - friction characterization\n  - material selection\n  - ASTM G98\nbibliography: refs.bib\ncsl: ieee.csl\n---\n\n# Summary {#sec-summary}\n\nThis test campaign ranks five material pairings for 1/4-80 UN adjusters used in optics-grade mechanisms that must run dry in N₂ at 26°C. The study captures friction torque, galling severity, particle generation, outgassing, resolution, and drift over 1×10⁶ cycles. Results feed two deliverables: a down-selection matrix identifying the top-performing pairing for flight hardware, and a calibrated friction-torque model accurate enough (τ ≥ 0.80, NRMSE ≤ 15%) to predict performance of future candidates without re-testing. The test drives the translation adjuster of a production crossed-roller stage inside a dry-nitrogen chamber, logging torque, micro-step position, and micron-resolution displacement. A constant 46.7 N spring preload ensures each candidate screw/nut/surface combination resists galling while maintaining stable friction and positional repeatability. All data, analysis code, and calibrated fixture CAD become available in an engineering-release package at project close.\n\n# Objective and Scope {#sec-objectives}\n\n## Objectives (what this test will do)\n\n::: {#tbl-objectives}\n\n| OBJ-ID | Objective | Requirement(s) verified |\n|--------|-----------|-------------------------|\n| OBJ-01 | Measure break-away torque vs cycle for five candidate pairings | TP05, BE03 |\n| OBJ-02 | Verify tip-tilt resolution ≤ 0.0025 mrad per µstep (L/R values) | TP01 |\n| OBJ-03 | Quantify particle generation relative to Krytox baseline | CLN |\n| OBJ-04 | Confirm pointing drift ≤ 0.030 mrad over ΔT = 4 °C | TP04 |\n| OBJ-05 | Demonstrate no missed steps with 0.50 N m motor at T_ba + 20 % | TP05 |\n| OBJ-06 | Correlate Simulink T_ba prediction to hardware (±25 %) | TP05 |\n| OBJ-07 | Validate μ(cycle) model to ±20 % after 25 cycles | — |\n\nTest objectives and linked requirements.\n:::\n\n::: {#tbl-traceability-objectives}\n\n| Obj-ID | Objective | Linked Claim(s) |\n|--------|-----------|------------------|\n| OBJ-01 | Rank each material pairing by Galling Severity Index (GSI) to identify the most wear-resistant interface. | C-002 |\n| OBJ-02 | Quantify steady-state and breakaway torque and prove the analytical model's ability to reproduce the ordering of those torques. | C-001 |\n| OBJ-03 | Rank pairings by particle emission rate (>0.5 µm) under ISO 14644 conditions. | C-003 |\n| OBJ-04 | Rank pairings by total mass-loss/outgassing per ASTM E595 after 72 h bake-out. | C-004 |\n| OBJ-05 | Rank pairings by Precision Performance Score (PPS) combining resolution and drift. | C-005 |\n\nObjective-to-claim traceability.\n:::\n\n::: {.callout-note}\n## Design Intent\n\n- **Hardware down-selection** -- Only the top-ranked pairing moves to flight builds; others are discarded.\n\n- **Model calibration** -- A validated friction-torque model prevents costly future bench testing.\n\n- **Contamination control** -- Rankings drive optical-surface lifetime predictions in the contamination budget.\n\n- **System reliability** -- Galling-resistant, low-particle interfaces safeguard long-term adjustability.\n:::\n\n## In-Scope Items\n\n- Five candidate material pairings listed in @tbl-material-pairings.\n\n- Dry-nitrogen atmosphere, 26°C ± 2°C.\n\n- Full-travel cycling (0-0.5 in) at 1 Hz for 1×10⁶ cycles.\n\n- Post-test microscopy, ISO particle counting, ASTM E595 TML/CI measurement.\n\n## Out-of-Scope Items\n\n- Temperature extremes outside 20-30°C.\n\n- Long-term radiation or UV exposure effects.\n\n- Alternate thread sizes or pitch variants.\n\n## Success Outputs\n\n- Ranked list and spider-chart summary for all five-performance metrics.\n\n- Calibrated analytical model with τ and NRMSE statistics.\n\n- Engineering-release ZIP: raw data, processed data, scripts, calibrated fixture CAD.\n\n# Claims to Validate {#sec-claims}\n\n::: {#tbl-claims}\n\n| Claim-ID | Formal Statement |\n|----------|------------------|\n| C-001 | The analytical friction-torque model reproduces the relative ordering and magnitude (within ±15%) of measured breakaway torques across all five material pairings. |\n| C-002 | Material pairings ranked by Galling Severity Index (GSI) show correlation coefficient r ≥ 0.85 with industry-standard ASTM G98 galling threshold stress measurements. |\n| C-003 | Median particle count >0.5 µm per cycle differs by statistically significant margins (p < 0.05) between the five candidate pairings, enabling clear ranking. |\n| C-004 | Total mass-loss/outgassing per ASTM E595 remains below 1.0% for all candidates, with Collected Volatile Condensable Material (CVCM) < 0.1%. |\n| C-005 | Precision Performance Score (PPS): resolution + drift metrics remain stable within ±10% over 25 cycles for at least three material combinations. |\n\nClaims under validation with formal acceptance statements.\n:::\n\n::: {#tbl-material-pairings tbl-colwidths=\"[10,18,22,18,32]\"}\n\n| Pairing ID | Male Component | Female Component | Surface Treatment | Expected Behavior |\n|------------|----------------|------------------|--------------------|-------------------|\n| MP-01 | 304 SS | Aluminum Bronze (C95400) | None | Baseline (unlubricated) - Expected severe galling |\n| MP-02 | 304 SS | Aluminum Bronze (C95400) | Krytox GPL 205 | Baseline (lubricated) - Control case |\n| MP-03 | 304 SS | Phosphor Bronze (C51000) | None | Moderate friction, reduced galling |\n| MP-04 | Nitronic 60 | Phosphor Bronze (C51000) | None | Low friction, minimal galling |\n| MP-05 | 304 SS (Kolsterised) | Phosphor Bronze (C51000) | None | Enhanced hardness, reduced adhesion |\n\nMaterial pairings under test.\n:::\n\n# Validation Strategy {#sec-validation}\n\n## Traceability Matrix\n\n::: {#tbl-traceability-matrix tbl-colwidths=\"[8,25,22,27,18]\"}\n\n| Claim-ID | Fixture Feature / Control | Data Collected | Validation Method | Pass/Fail Metric |\n|----------|---------------------------|----------------|-------------------|------------------|\n| C-001 | Inline torque transducer (FUTEK TFF400); Micro-step position counter; Constant 46.7 N preload | Time-series torque data; Peak breakaway torque per cycle; Running torque | MATLAB friction model with wear-in and galling progression equations compared to measured torque curves | Model predicts relative ordering correctly AND magnitude within ±15% for all pairings |\n| C-002 | N₂-purged test chamber; Production-grade stage with matched preload springs; 25+ cycles per pairing | Torque vs. cycle plots; Thread surface images at 10× magnification; Material transfer quantification | Computed GSI = (ΔT/T₀)×(Nᵥᵢₛ/25)×100% where ΔT = torque increase, T₀ = initial torque, Nᵥᵢₛ = cycles before visible damage | GSI correlates with published ASTM G98 thresholds with r ≥ 0.85 |\n| C-003 | ISO Class 5 environment; Particle counter sampling port; Standardized cycle protocol | Particle count >0.5 µm per cycle; Size distribution histogram; Time-series data | Statistical comparison (ANOVA) of median particle counts across material pairs with post-hoc tests | p < 0.05 for differences between pairings |\n| C-004 | Specimen preparation per ASTM E595; Vacuum chamber with cold plate | TML (%); CVCM (%); Water Vapor Regained (WVR, %) | Standard ASTM E595 protocol with 125°C sample temperature, 25°C collector | TML < 1.0% AND CVCM < 0.1% for all candidates |\n| C-005 | Laser displacement sensor (0.1 µm resolution); Standardized dwell periods (5 min) | Linear position vs. commanded position; Position error after dwell; Repeatability statistics | PPS = 10×(1-RMS₁/RMS₀)+(1-Δd/d₀) where RMS terms are positional errors and Δd is drift | PPS stability within ±10% over 25 cycles for ≥3 pairings |\n\nFull traceability from claims to fixture features, data, validation method, and pass/fail criteria.\n:::\n\n## Validation Narrative\n\nThe validation strategy creates a direct chain of evidence linking each claim to measurable test outcomes:\n\n::: {.callout-tip title=\"Validation: Claim C-001 (Model Fidelity)\"}\nThe inline torque transducer captures real-time torque data with high precision (0.05% repeatability) while the micro-stepping controller tracks angular position. These data streams feed the friction model, which predicts torque behavior based on material properties and wear mechanisms. The model passes validation when it correctly orders the pairings by friction torque magnitude and predicts values within ±15% of measured values, demonstrating sufficient accuracy for future predictions without bench testing.\n\nThe model incorporates both static and dynamic friction coefficients for each material pairing, building on established tribological relationships for threaded interfaces. Initial friction values derive from literature (e.g., μ≈0.34 for 304 SS on phosphor bronze), but the model adapts these values based on actual test data. The wear-in relation in Eq. @eq-wearin accounts for surface conditioning during early cycles, while the galling progression relation in Eq. @eq-galling captures the exponential torque increase seen in failing interfaces. This dual-mode approach ensures accurate prediction of both normal wear and incipient galling.\n:::\n\n::: {.callout-tip title=\"Validation: Claim C-002 (Galling Severity)\"}\nThe Galling Severity Index (GSI) calculation combines torque progression data with visual inspection to quantify galling resistance. By conducting tests in a controlled N₂ environment with identical preload conditions (46.7 N) to the flight hardware, the GSI values directly represent real-world performance. The correlation with ASTM G98 [@astm_g98] standard test results validates that the simplified GSI approach captures the same fundamental galling behavior as industry-standard methods.\n\nThe GSI formula in Eq. @eq-gsi incorporates both torque increase (indicating friction change due to surface damage) and the number of cycles before visible thread damage appears under 10× magnification. This dual approach improves upon traditional single-parameter assessments by combining functional performance with physical evidence. Previous studies show strong correlation between similar indices and standard ASTM G98 galling thresholds for various material combinations. Visual inspection utilizes standardized reference images for consistent rating of damage severity.\n:::\n\n::: {.callout-tip title=\"Validation: Claim C-003 (Particle Generation)\"}\nThe ISO Class 5 environment and particle counter provide a clean baseline to detect particles generated solely by thread interaction. The standardized cycle protocol ensures fair comparison across all material pairings. Statistical analysis verifies that observed differences are significant and not due to random variation, enabling a definitive ranking for contamination-sensitive applications.\n\nParticle counting employs both time-series and cumulative methods. The optical particle counter samples chamber air through an isokinetic probe positioned near the threads, capturing particles generated during operation. Size bins (0.5, 1.0, 5.0 μm) align with ISO 14644 [@iso_14644] standards and typical optical contamination concerns. Background counts establish the detection floor, with all test measurements compensated for baseline contamination. The ANOVA analysis confirms that observed differences between material pairs represent true performance variations rather than random fluctuations or measurement error.\n:::\n\n::: {.callout-tip title=\"Validation: Claim C-004 (Outgassing)\"}\nASTM E595 [@astm_e595] testing provides standardized outgassing metrics critical for vacuum and optical applications. The TML and CVCM thresholds represent established aerospace standards for acceptable materials. Testing validates that all candidate pairings meet these requirements, ensuring optical cleanliness in the nitrogen-purged environment.\n\nSample preparation follows strict ASTM protocols, with test articles cleaned identically to flight hardware. The 125°C sample temperature accelerates outgassing, while the 25°C collector plate captures condensable species. This represents a worst-case scenario compared to the 26°C operational environment. Water Vapor Regained (WVR) measurement distinguishes between water vapor and true material outgassing, providing additional insight into long-term behavior. While all metal-on-metal interfaces should theoretically exhibit minimal outgassing, this verification ensures no unexpected surface contamination or treatment residues are present.\n:::\n\n::: {.callout-tip title=\"Validation: Claim C-005 (Precision Performance)\"}\nThe laser displacement sensor directly measures the actual position achieved versus commanded position, capturing any resolution loss or drift. The Precision Performance Score in Eq. @eq-pps combines two key precision metrics---positional error and drift after dwell---into a single figure of merit. Stability of this score over 25 cycles proves the mechanical interface maintains precision throughout its operational life.\n\nThe PPS formula weighs both immediate positioning accuracy (RMS position error) and temporal stability (drift after dwell). These factors directly impact optical alignment capabilities. The 5-minute dwell period simulates a realistic operational scenario where the adjuster remains still between occasional adjustments. This test reveals any tendency for the interface to creep due to stress relaxation or microscopic settling. By tracking PPS across multiple cycles, the test also captures any degradation in precision due to progressive wear or surface changes.\n:::\n\nThis multi-faceted validation approach ensures that all critical performance aspects---friction, wear resistance, contamination risk, and precision---undergo rigorous evaluation, delivering comprehensive data for material selection.\n\n# Test Fixture Design {#sec-fixture}\n\n## Overview\n\nThe test fixture integrates a production-grade crossed-roller stage with precision measurement systems inside a nitrogen-purged chamber. @fig-fixture shows the key components.\n\n![Test fixture layout showing the stepper motor drive train, inline torque sensor, crossed-roller stage, and nitrogen purge chamber.](figures/fixture-schematic.png){#fig-fixture fig-alt=\"Test fixture schematic showing stepper motor, torque sensor, and stage assembly inside nitrogen chamber\"}\n\nThe fixture design employs a horizontal drive arrangement with the motor shaft aligned with the adjuster's rotation axis. The translation block rides on crossed-roller bearings providing high axial stiffness with minimal friction. The rotation block remains clamped during translation testing to isolate a single degree of freedom. This configuration creates a clean, single-axis test with the adjuster thread friction as the dominant variable between test cases.\n\n## Critical Features\n\nThe fixture incorporates several design features specifically aligned with validation requirements:\n\n1.  **Stepper Motor Drive Train** (supports C-001, C-005): A precision 0.9° stepper motor (StepperOnline 23HM22-2804S) with 1.26 N·m holding torque connects to the adjuster via a bellows coupling and torque cell. With 32× microstepping, the theoretical angular resolution reaches 25 nrad (≈0.025 µin linear motion), allowing detection of the finest stick-slip behavior.\n\n    The motor provides significantly more torque (1.26 N·m) than required for normal operation (typically <0.2 N·m) to ensure adequate headroom for detecting galling-induced torque spikes. The precision step angle (0.9° versus standard 1.8°) doubles the base resolution, while the microstepping driver further subdivides each step into 32 micro-positions. This ultra-fine positioning capability enables detection of microscopic stick-slip events that would be masked by coarser motion control.\n\n2.  **Inline Torque Transducer** (supports C-001, C-002): The FUTEK TFF400-05 torque sensor (±0.04 N·m range) measures real-time torque at 1 kS/s, capturing both breakaway peaks and running friction. The sensor's 0.05% non-repeatability enables detection of subtle changes in thread condition throughout the test.\n\n    The through-hole design allows direct mounting between couplings without introducing alignment errors or additional friction. The sensor's metal-foil strain gauge technology ensures stable readings even under prolonged testing, with negligible drift over the test duration. The high sampling rate (1 kS/s) captures transient events during breakaway, providing detailed friction signatures for each material pairing.\n\n3.  **Nitrogen Purge Chamber** (supports C-002, C-003, C-004): An acrylic enclosure with O-ring seals and gas ports maintains <50 ppm O₂ to replicate the inert environment of the flight hardware. The 2 SLPM purge flow ensures consistent atmospheric conditions while allowing particle extraction for counting.\n\n    The chamber volume (approximately 1 L) permits complete atmosphere exchange within 30 seconds at the specified flow rate. The clear acrylic construction enables visual monitoring during testing while maintaining a sealed environment. Gas inlets incorporate sintered metal diffusers to minimize turbulence and prevent direct gas impingement on the test articles, which could disperse particles or create artificial airflow patterns.\n\n4.  **Production-Grade Stage** (supports C-002, C-005): Using the actual flight-configuration crossed-roller stage with proper spring preload (46.7 N) creates authentic boundary conditions. The stage's translation block houses the 1/4-80 female thread component, while the ball-tipped adjuster screw represents the male component under test.\n\n    The crossed-roller bearings provide extremely high stiffness in five degrees of freedom while allowing low-friction motion in the travel direction. This kinematic design isolates thread friction effects from other mechanical variables. The stage includes 440C hardened stainless steel ball tips contacting sapphire pads---a proven low-friction, wear-resistant interface that ensures the ball-tip contact is not a limiting factor in the test.\n\n5.  **Laser Displacement Sensor** (supports C-005): A Keyence LK-G152 laser triangulation sensor with 0.1 µm resolution monitors the actual position of the translation block, detecting any position errors or drift caused by thread friction or wear.\n\n    The non-contact measurement eliminates any influence on the mechanical system while providing traceable position data. With 50 kHz sampling capability, the sensor captures micro-dynamic behavior, including any momentary position reversals or oscillations. The 120 µm spot size averages surface irregularities while maintaining sufficient spatial resolution for detecting the smallest relevant motions.\n\n6.  **Particle Sampling Port** (supports C-003): A calibrated isokinetic sampling port extracts a representative air sample from the chamber to an external optical particle counter, quantifying particles generated during thread operation.\n\n    The port design maintains equivalent velocity between chamber air and sampled stream, ensuring accurate particle concentration measurement without size bias. The sampling location sits 25 mm from the thread interface---close enough to capture generated particles before they disperse but far enough to avoid sampling only localized concentrations.\n\n7.  **Granite Base Plate** (supports all claims): A 100 mm × 150 mm × 25 mm granite slab provides thermal stability and vibration isolation for the entire test assembly.\n\n    The granite's high thermal mass dampens temperature fluctuations, maintaining stable dimensional relationships between components. Its flatness (±2 µm) and stability serve as a solid reference for all measurements. Stainless steel dowel pins precisely locate the stage components on the granite base, ensuring repeatable positioning between test configurations.\n\n8.  **Motion Controller** (supports C-001, C-005): A Trinamic TMCM-1230 controller provides precise motor control with advanced current sensing capabilities that serve as a secondary measure of motor torque.\n\n    The controller's 256× microstepping capability delivers ultra-smooth motion while its StallGuard feature offers real-time detection of mechanical resistance. The RS-485 interface enables high-speed communication with the data acquisition system, synchronizing motion commands with sensor measurements. The controller includes programmable acceleration profiles that minimize vibration during direction changes.\n\n## Assumptions and Design Limits\n\nThe fixture design operates under the following constraints and assumptions:\n\n- **Materials**: 440C hardened stainless steel ball tips on adjusters (HRC 58-60) contacting sapphire pads. These create a Hertzian contact with 3.2 GPa peak pressure that forms a stable interface after initial plastic deformation.\n\n    The high hardness of both materials ensures the ball-pad interface contributes minimal friction or wear to the system. The 440C ball undergoes limited plastic deformation during initial loading, creating a stable contact patch with the sapphire. This plastic zone extends only a few microns into the ball surface and does not progress during normal operation. Sapphire's extreme hardness (>2000 HV) ensures it remains fully elastic under the applied load.\n\n- **Load Range**: Spring preload of 46.7 N (10.5 lbf) based on three parallel springs each with k = 17.5 lbf/in stretched 0.200 inches. Maximum torque capacity of the sensor is 0.35 N·m, sufficient for normal operation but may saturate if severe galling occurs.\n\n    The preload applies directly along the adjuster axis, creating a pure axial force with no side loading. This force maintains positive contact between the ball tip and sapphire pad throughout the test range. The spring constant creates a nearly constant force over the travel range, with less than 5% variation across the full stroke. The torque sensor includes 150% overload protection, allowing brief excursions beyond the rated range without damage.\n\n- **Measurement Resolution**:\n\n  - Angular: 28.8 μrad per full-step (0.9 μrad with 32× microstepping)\n  - Linear: 0.1 μm (displacement sensor)\n  - Torque: 0.01 mN·m (24-bit acquisition of ±0.04 N·m range)\n  - Cycle counting: ±0 error (absolute encoder)\n\n    These resolution values exceed the requirements for detecting relevant performance differences between material pairings. For context, a 0.1 μm linear resolution represents approximately 0.002% of the full 0.5-inch travel range. The torque resolution (0.01 mN·m) equates to approximately 0.025% of the expected operating range, enabling detection of subtle friction changes.\n\n- **Thermal Stability**: Test environment maintains 26°C ± 2°C. The granite base provides thermal mass to dampen fluctuations. Differential thermal expansion between materials over this range causes negligible dimensional changes (<0.1 μm).\n\n    The small temperature range minimizes thermal effects on friction coefficients, which typically vary by less than 5% over this span for the materials under consideration. The similar thermal expansion coefficients of stainless steel (≈16×10⁻⁶/°C) and bronze alloys (≈17×10⁻⁶/°C) result in minimal differential expansion, preserving thread clearances throughout the test.\n\n- **Boundary Conditions**: The translation block motion is constrained by crossed-roller bearings with stiffness >10⁷ N/m. The rotation block remains clamped during translation tests to isolate a single degree of freedom.\n\n    This high stiffness ensures that measured displacements directly correspond to adjuster motion without significant elastic deformation of the fixture. The crossed-roller bearing friction (<0.01 N) contributes negligibly to the measured torque compared to thread friction forces (typically >1 N). The clamping of the rotation block eliminates potential crosstalk between the two adjustment axes.\n\n- **Nitrogen Environment**: Purge gas is 99.995% pure N₂ with <5 ppm O₂, <3 ppm H₂O, and particulate filtration to <0.003 μm. The chamber maintains positive pressure (~25 Pa) relative to the laboratory.\n\n    This high-purity environment prevents oxide formation on freshly exposed metal surfaces, simulating the conditions that promote galling in space mechanisms. The positive pressure prevents laboratory air ingress, maintaining consistent atmospheric composition throughout testing. The extreme dryness (<3 ppm H₂O) eliminates any boundary lubrication effects from adsorbed water vapor.\n\n- **Sampling Statistics**: Each test configuration runs for 25 cycles minimum, with three specimens per material pairing. This provides 75 data points per configuration for statistical analysis.\n\n    This sample size delivers 90% confidence in detecting a 15% difference between material pairings with 80% statistical power. The multiple specimens account for manufacturing variations and provide a basis for assessing repeatability. Extended life testing (up to 10⁶ cycles) runs on only the top-performing specimen from each pairing.\n\n# Test Procedure {#sec-procedure}\n\n## Pre-test Calibration and Checks\n\n1.  Perform zero-load calibration of the FUTEK torque transducer using the supplied calibration shunt.\n\n2.  Verify laser displacement sensor calibration using a certified gage block.\n\n3.  Mount a reference screw/nut pair (304 SS/Al-bronze with Krytox) for system verification.\n\n4.  Apply 46.7 N preload using the spring pack and verify with load cell.\n\n5.  Perform three reference cycles and confirm torque values within 5% of expected range.\n\n6.  Clean the test chamber with isopropyl alcohol and lint-free wipes.\n\n7.  Perform particle background count; verify ISO Class 5 or better (<3,520 particles >0.5 μm per m³).\n\n8.  Verify stepper motor step accuracy using the displacement sensor over 10 complete revolutions.\n\n9.  Check the nitrogen delivery system for proper flow rate (2 SLPM) and pressure regulation.\n\n10. Verify data acquisition system timing and synchronization using a square wave test signal.\n\n11. Confirm temperature stability within the test chamber (26°C ± 0.5°C) over a 30-minute period.\n\n12. Document initial condition of all test articles with 10× digital microscopy.\n\n## Step-by-step Execution\n\nFor each candidate material pairing:\n\n1.  Install the male adjuster screw in the drive coupling.\n\n2.  Insert the female threaded component in the translation block.\n\n3.  Close the acrylic chamber.\n\n4.  Purge with nitrogen at 2 SLPM until O₂ < 50 ppm.\n\n5.  Home the stepper motor to the starting position.\n\n6.  Record start time and configuration details in the test log.\n\n7.  Drive the adjuster +0.25 turn at 1 RPM.\n\n8.  Hold position for 5-minute dwell period.\n\n9.  Drive the adjuster -0.25 turn at 1 RPM to complete one cycle.\n\n10. Repeat steps 7-9 for 25 consecutive cycles.\n\n11. For extended life testing, continue cycling at 1 Hz for 1×10⁶ cycles or until failure.\n\n12. Vent the chamber and remove the test components.\n\n13. Photograph thread surfaces at 10× magnification using the digital microscope.\n\n14. Package threads in sealed containers for subsequent ASTM E595 [@astm_e595] testing.\n\n15. Clean fixture components before installing the next pairing.\n\nFor detailed characterization of friction behavior:\n\n16. During the first, fifth, tenth, and twenty-fifth cycles, drive the adjuster in 0.05° increments.\n\n17. Record torque at each position to generate high-resolution torque-angle curves.\n\n18. After each dwell period, measure the torque required to initiate motion (breakaway torque).\n\n19. Calculate the difference between forward and reverse torque to quantify hysteresis.\n\n20. Monitor any stick-slip behavior by analyzing torque oscillations during constant-speed rotation.\n\nFor extended cycling tests:\n\n21. Program the controller to execute 1 Hz reciprocating cycles covering the full 0.5-inch travel.\n\n22. Configure automated data sampling to record complete cycles at logarithmic intervals (cycles 1, 10, 100, 1000, etc.).\n\n23. Set torque limit thresholds to automatically halt testing if galling-induced torque spikes occur.\n\n24. Verify nitrogen flow and temperature stability every 8 hours during extended runs.\n\n25. Perform interim inspections at 1,000, 10,000, and 100,000 cycles for long-duration tests.\n\n## Data Logging Requirements\n\n- **Torque Data**: Sample at 1 kS/s with synchronous timestamps. Record both raw and filtered values. File format: `{date}_torque_{material-ID}.csv`\n\n- **Position Data**: Sample angular position at 1 kS/s to match torque data; sample linear displacement at 5 kS/s. File format: `{date}_position_{material-ID}.csv`\n\n- **Environmental Data**: Log N₂ purity, temperature, and relative humidity at 1 Hz. File format: `{date}_environment_{material-ID}.csv`\n\n- **Particle Data**: Log particle counts by size bin (0.5, 1.0, 5.0 μm) at 1 Hz. File format: `{date}_particles_{material-ID}.csv`\n\n- **Metadata**: Record all test configuration details, sample IDs, and timestamps in a structured JSON file. Format: `{date}_metadata_{material-ID}.json`\n\nAll data files require SHA-256 checksums for integrity verification.\n\n```{.csv filename=\"torque-data-columns.csv\"}\nTimestamp (μs precision)\nRaw torque (N·m)\nFiltered torque (N·m)\nMotor phase current (A)\nDerived friction coefficient (calculated in real-time)\n```\n\n```{.csv filename=\"position-data-columns.csv\"}\nTimestamp (μs precision)\nCommanded angle (degrees)\nActual angle (encoder reading, degrees)\nLinear position (μm)\nPosition error (μm)\n```\n\n```{.csv filename=\"environment-data-columns.csv\"}\nTimestamp (s precision)\nO₂ concentration (ppm)\nN₂ flow rate (SLPM)\nTemperature (°C)\nRelative humidity (%)\nPressure (kPa)\n```\n\n```{.yaml filename=\"metadata-schema.json\"}\nmaterial_pairing_id: MP-XX\ncomponent_serial_numbers: [...]\noperator_name: \"\"\noperator_contact: \"\"\ncalibration_certificate_refs: [...]\ntest_sequence_number: 0\nnotes_or_anomalies: \"\"\nsoftware_firmware_versions: {}\n```\n\nImage data:\n\n- Pre-test microscopy: `{date}_pre_{material-ID}_{location}.tif` (16-bit)\n- Post-test microscopy: `{date}_post_{material-ID}_{location}.tif` (16-bit)\n- Thread profile scans (if applicable): `{date}_profile_{material-ID}.csv`\n\n## Post-test Teardown / Safety\n\n1.  Verify the nitrogen purge system is deactivated and chamber vented.\n\n2.  Remove all test articles and place in labeled, sealed containers.\n\n3.  Disconnect the torque sensor to prevent accidental damage.\n\n4.  Clean the fixture with isopropyl alcohol and lint-free wipes.\n\n5.  Cover all optical surfaces with protective caps.\n\n6.  Verify all power is disconnected from the motion control system.\n\n7.  Complete post-test inspection checklist documenting fixture condition.\n\n8.  Transfer all collected data to the secure repository with backup.\n\n9.  Log the total test duration and cycle count in the test record.\n\n10. Update the master test matrix with completion status.\n\n11. For components showing significant galling or damage, apply corrosion inhibitor before storage.\n\n12. Prepare selected components for subsequent ASTM E595 outgassing tests.\n\n13. Document any fixture maintenance or calibration needs discovered during testing.\n\n14. Remove and properly dispose of any particles or debris from the test chamber.\n\n15. Secure the testing area and return all tools to designated storage.\n\n# Data Analysis Plan {#sec-analysis}\n\n## Raw-to-processed Data Pipeline\n\nThe analysis workflow processes the raw data files through several steps:\n\n1.  **Signal Conditioning**: Apply a 5th-order Butterworth low-pass filter with 20 Hz cutoff to the torque data to eliminate motor and electronic noise while preserving breakaway peaks.\n\n2.  **Breakaway Torque Extraction**: Identify the peak torque occurring within the first 5° of motion after each dwell period using a peak-detection algorithm with a slope threshold of 0.1 N·m/s.\n\n3.  **Steady-state Torque Calculation**: Average the torque values between 10° and 90° of each rotation to determine running friction, excluding the initial breakaway region and end-of-travel effects.\n\n4.  **Torque Progression Analysis**: Plot peak breakaway torque vs. cycle number for each material pairing and fit to the appropriate model:\n\n    For non-galling cases:\n\n    $$\n    T(n) = T_{0} + (T_{s} - T_{0})(1 - e^{-kn})\n    $$ {#eq-wearin}\n\n    where $T_{s}$ is steady-state torque.\n\n    For galling cases:\n\n    $$\n    T(n) = T_{0} + ae^{bn}\n    $$ {#eq-galling}\n\n    where $a,b$ are growth parameters.\n\n5.  **Position Error Analysis**: Calculate the difference between commanded and actual position at each micro-step, generating an error histogram and RMS error value per cycle.\n\n6.  **Particle Data Processing**: Convert raw particle counts to particles/cycle and particles/mm of travel to normalize for comparison.\n\n7.  **Friction Coefficient Derivation**: Calculate the effective friction coefficient for each material pairing using the torque and preload data via:\n\n    $$\n    \\mu = \\frac{T}{F_{N}r_{\\text{eff}}}\n    $$ {#eq-torque-friction}\n\n    where $r_{\\text{eff}}$ is the effective radius for the 1/4-80 thread geometry.\n\n8.  **Hysteresis Analysis**: Calculate the area enclosed by the torque-vs-angle curve during forward and reverse motion to quantify energy loss per cycle.\n\n9.  **Stick-Slip Characterization**: Analyze torque time derivatives to identify and quantify stick-slip events, recording amplitude and frequency.\n\n10. **Thread Surface Analysis**: Process microscopy images through computational methods to quantify surface roughness changes, material transfer volume, and wear track dimensions.\n\n11. **Time-series Alignment**: Synchronize all data streams based on timestamps to create composite visualizations of torque, position, and particle generation.\n\n12. **Data Cleaning**: Apply statistical outlier detection to identify and flag anomalous measurements for review. Employ Hampel filtering for spike removal while preserving genuine torque peaks.\n\n## Statistical Tests and Models\n\n1.  **ANOVA with Tukey HSD Post-hoc Tests**: Determine statistically significant differences in breakaway torque, steady-state torque, and particle generation between material pairings.\n\n2.  **Correlation Analysis**: Calculate Pearson's r between measured GSI values and published ASTM G98 [@astm_g98] galling thresholds to validate Claim C-002.\n\n3.  **Predictive Model Evaluation**: Calculate Kendall's τ and NRMSE between predicted and measured torque values to quantify model accuracy for Claim C-001.\n\n4.  **Weibull Analysis**: Apply Weibull statistics to lifetime data from extended cycles to predict failure probability at various cycle counts.\n\n5.  **Precision Performance Score Calculation**: Compute PPS per @eq-pps for each cycle and material pairing, then perform stability analysis.\n\n6.  **Bootstrap Confidence Intervals**: Generate 95% confidence intervals for all key metrics using bootstrap resampling to account for measurement uncertainty.\n\n7.  **Principal Component Analysis**: Apply PCA to the multi-dimensional performance data to identify key factors driving material pairing differences.\n\n8.  **Cox Proportional Hazards Model**: For extended life testing, apply survival analysis techniques to quantify reliability differences between material pairings.\n\n9.  **CUSUM Analysis**: Apply cumulative sum control charts to detect subtle shifts in friction behavior that might indicate incipient galling.\n\n10. **Multiple Regression Analysis**: Develop a multi-factor model relating material properties (hardness, surface roughness) to measured performance metrics.\n\n## Acceptance Criteria\n\nEach claim's pass/fail metric maps to specific acceptance criteria:\n\n::: {.callout-important title=\"Acceptance: C-001 (Model Fidelity)\"}\nThe model passes if:\n\n- The predicted rank order of breakaway torques matches the measured order exactly.\n- The predicted magnitudes fall within ±15% of measured values for all five pairings.\n- The NRMSE between predicted and measured torque progression curves is ≤15%.\n\nThis requires consistent behavior across test specimens and good agreement between model predictions and measurement. The analytical model must capture both the initial friction levels and the friction evolution trends correctly to pass validation.\n:::\n\n::: {.callout-important title=\"Acceptance: C-002 (Galling Severity)\"}\nAcceptance requires:\n\n- Pearson's r ≥ 0.85 between calculated GSI values and published ASTM G98 [@astm_g98] thresholds.\n- Clear visual differentiation in 10× microscopy images correlating with GSI ranking.\n- At least two material pairings show GSI < 10 (minimal galling) after 25 cycles.\n\nThe GSI calculation must provide a quantitative measure that aligns with established galling assessment methods. The visual inspection criterion ensures that numerical results correspond to physical reality. The requirement for at least two viable pairings ensures the test identifies multiple potential solutions.\n:::\n\n::: {.callout-important title=\"Acceptance: C-003 (Particle Generation)\"}\nValidation requires:\n\n- ANOVA p < 0.05 for differences in particle generation rates between pairings.\n- At least two pairings show particle generation rates <100 particles (>0.5 μm) per cycle.\n- Consistent particle size distribution for each material pairing across all test cycles.\n\nStatistical significance ensures the observed particle generation differences are real, not artifacts of measurement variation. The absolute threshold (<100 particles/cycle) represents a practical clean-room compatibility target. Consistency in size distribution confirms that the particle generation mechanism remains stable throughout testing.\n:::\n\n::: {.callout-important title=\"Acceptance: C-004 (Outgassing)\"}\nAcceptance criteria include:\n\n- All candidates demonstrate TML < 1.0% per ASTM E595 [@astm_e595].\n- All candidates show CVCM < 0.1% per ASTM E595 [@astm_e595].\n- Water Vapor Regained (WVR) is reported but has no pass/fail threshold.\n\nThese thresholds align with NASA [@nasa_outgassing] standards for space-qualified materials. TML measures total mass loss under vacuum, while CVCM quantifies condensable materials that could contaminate optical surfaces. WVR provides context for interpreting TML results, as water vapor resorption is generally less concerning than true material outgassing.\n:::\n\n::: {.callout-important title=\"Acceptance: C-005 (Precision Performance)\"}\nValidation requires:\n\n- PPS stability within ±10% over 25 cycles for at least three material combinations.\n- At least one pairing achieves an average PPS > 18 (out of theoretical maximum 20).\n- Position drift after 5-minute dwell <0.5 μm for the top-performing pairing.\n\nStability in the PPS metric indicates consistent mechanical performance over repeated use. The absolute score threshold (>18) ensures at least one solution meets high precision requirements. The drift specification (<0.5 μm) represents a practical limit for optical alignment applications, where positional stability directly impacts system performance.\n:::\n\n# Risk Assessment and Mitigations {#sec-risk}\n\n::: {#tbl-risk}\n\n| Risk | Potential Impact | Mitigation Strategy |\n|------|------------------|---------------------|\n| Premature thread seizing | Test interruption, data loss, fixture damage | Monitor torque in real-time with automatic cutoff at 1.5× baseline; keep spare components for all material pairings |\n| Torque sensor overload | Sensor damage, calibration loss | Include mechanical torque limiter (slip clutch) set to 0.3 N·m; implement software limits in motor controller |\n| Nitrogen supply interruption | Environment change, test invalidation | Use pressure sensor with alarm; incorporate backup N₂ cylinder with automatic switchover |\n| Contamination between tests | Cross-sample contamination, invalid results | Establish rigorous cleaning protocol with verification; use separate tools for each material set |\n| Power interruption | Data loss, test restart required | Employ UPS for all electronics; enable auto-save of data every 60 seconds; implement auto-recovery procedure |\n| Temperature fluctuation | Changed friction behavior, invalid comparisons | Monitor temperature continuously; flag data if excursion >±1°C; incorporate in analysis as covariate |\n| Particle counter malfunction | Missing contamination data | Perform verification count before each pairing; have backup counter available |\n| Ball-tip deformation | Changed contact geometry, invalid results | Inspect ball tips before testing; replace if any visible wear; perform Hertzian stress calculation to confirm safe operating regime |\n| Thread alignment issues | Side loading, invalid torque readings | Use precision fixtures to ensure coaxial alignment; monitor lateral displacement during tests |\n| DAQ sampling errors | Data gaps or artifacts | Implement circular buffer to prevent data loss; check timestamps for continuity during post-processing |\n| Laser sensor misalignment | Inaccurate position data | Mount sensor on kinematic base; verify calibration before each test series; monitor return signal strength |\n| Thread manufacturing variability | Inconsistent baseline performance | Source all test components from same manufacturing lot; measure and document thread profile before testing |\n| Inadequate sample size | Reduced statistical confidence | Test minimum three specimens per material pairing; use power analysis to verify detection capability |\n| Fixture resonance | Vibration affecting measurements | Perform modal analysis before testing; add damping if needed; filter data at identified resonant frequencies |\n| Controller communication faults | Command/data synchronization issues | Implement watchdog timer and handshaking; verify timing with oscilloscope before test series |\n| Environmental contamination | Elevated background particle counts | Purge chamber for extended period before testing; verify ISO Class 5 conditions; conduct tests in cleanroom |\n| Drift in sensor calibration | Measurement accuracy degradation | Perform calibration checks at beginning and end of each test day; apply correction factors if needed |\n| Unexpected material behavior | Results not matching literature | Characterize actual material properties (hardness, roughness, composition) for all test samples |\n| Software bugs in analysis code | Incorrect results or interpretation | Implement unit tests for analysis functions; validate with synthetic data; conduct peer code review |\n| Mechanical wear of test fixture | Changing boundary conditions | Establish baseline reference runs; inspect fixture components regularly; replace critical elements preventively |\n\nRisk assessment with mitigation strategies for the validation campaign.\n:::\n\n# Deliverables and Schedule {#sec-deliverables}\n\n## Deliverables\n\n1.  **Test Report Package**:\n\n    - Comprehensive test report with executive summary and detailed results\n    - Raw data files for all measurements (torque, position, particles, environment)\n    - Processed data and statistical analysis outputs\n    - High-resolution microscopy images of thread surfaces pre/post-test\n    - ASTM E595 outgassing test certificates\n\n2.  **Engineering Model Package**:\n\n    - Calibrated MATLAB/Simulink model files\n    - Parameter sets for all material pairings\n    - Validation documentation comparing model predictions to test results\n    - User guide for applying the model to new configurations\n\n3.  **Test Fixture Package**:\n\n    - CAD files of the calibrated test fixture\n    - Bill of materials with supplier information\n    - Calibration certificates for all sensors\n    - Assembly and operation manual\n\n4.  **Spider-chart Summary Tool**:\n\n    - Interactive visualization tool for comparing material pairings\n    - Export functionality for reports and presentations\n    - Source code and documentation\n\n5.  **Material Selection Guide**:\n\n    - Detailed recommendations for optimal pairing selection based on application requirements\n    - Decision tree for evaluating new material combinations\n    - Case studies demonstrating selection process\n\n6.  **Extended Life Data**:\n\n    - Full cycle-to-failure data for top performers\n    - Weibull analysis and lifetime prediction models\n    - Failure mode documentation with supporting imagery\n\n7.  **Analytical Methods Documentation**:\n\n    - Detailed description of GSI calculation methodology\n    - Friction model derivation and validation\n    - Statistical analysis procedures and code examples\n\n8.  **Physical Specimens**:\n\n    - Archive set of tested specimens for future reference\n    - Cross-sectioned samples showing wear patterns and material transfer\n    - Reference samples of unworn components\n\n## Schedule\n\n::: {#tbl-schedule}\n\n| Milestone | Timeline | Dependencies |\n|-----------|----------|--------------|\n| Test fixture fabrication | Weeks 1-3 | Procurement of sensors and materials |\n| Fixture calibration | Week 4 | Completion of fabrication |\n| Baseline material testing | Week 5 | Calibrated fixture |\n| Candidate pairing tests | Weeks 6-8 | Preparation of all material samples |\n| Extended life testing | Weeks 9-15 | Completion of initial 25-cycle tests |\n| ASTM E595 testing | Weeks 9-11 | Completion of mechanical tests |\n| Data analysis | Weeks 16-18 | All test data collected |\n| Model calibration | Weeks 19-20 | Completed data analysis |\n| Final report and deliverables | Weeks 21-22 | All preceding tasks |\n| Engineering review | Week 23 | Final report completion |\n| Material selection recommendation | Week 24 | Engineering review approval |\n| Test fixture documentation | Weeks 21-22 | Parallel to final report |\n| Code and model documentation | Weeks 19-22 | During model calibration and report preparation |\n| Physical sample preparation | Weeks 18-20 | After completion of all mechanical testing |\n| Archiving and transfer | Week 24 | After engineering review |\n\nProject schedule with milestones and dependencies.\n:::\n\n# References {.unnumbered}\n\n::: {#refs}\n:::\n\n# Appendices {.appendix #sec-appendices}\n\n## Torque Sensor Specifications {#sec-appendix-torque}\n\n### A.1 Torque Sensor\n\n- **Model**: FUTEK TFF400-05\n- **Range**: ±0.04 N·m\n- **Accuracy**: 0.5% of rated output\n- **Non-repeatability**: 0.05% of rated output\n- **Excitation**: 5-12 VDC\n- **Output**: 2 mV/V nominal\n- **Temperature compensation**: 21°C to 32°C\n- **Overload capacity**: 150% of rated capacity\n- **Bridge resistance**: 350 Ω nominal\n- **Nonlinearity**: ±0.1% of rated output\n- **Hysteresis**: ±0.1% of rated output\n- **Temperature effect on zero**: 0.03% of rated output/°C\n- **Temperature effect on span**: 0.03% of rated output/°C\n- **Insulation resistance**: >500 MΩ @ 50 VDC\n- **Connector**: 4-pin LEMO\n- **Material**: Aluminum housing, stainless steel shaft\n- **Weight**: 130 g\n\n## Displacement Sensor Specifications {#sec-appendix-displacement}\n\n### A.2 Displacement Sensor\n\n- **Model**: Keyence LK-G152\n- **Measuring range**: ±40 mm\n- **Resolution**: 0.1 μm\n- **Sampling frequency**: 50 kHz\n- **Light source**: 650 nm semiconductor laser\n- **Spot diameter**: 120 μm\n- **Linearity**: ±0.05% of F.S.\n- **Temperature drift**: 0.01% F.S./°C\n- **Protection rating**: IP67\n- **Output**: ±10V analog, 16-bit digital\n- **Laser class**: Class 2 (IEC60825-1)\n- **Environmental resistance**: IP67\n- **Operating environment**: 0-50°C\n- **Controller**: LK-G5000 with Ethernet/IP interface\n- **Sample averaging**: 1-32768 samples (adjustable)\n- **Filter functions**: Moving average, median, low-pass\n\n## Particle Counter Specifications {#sec-appendix-particle}\n\n### A.3 Particle Counter\n\n- **Measurement range**: 0.5 μm to 25 μm\n- **Flow rate**: 2.83 L/min (0.1 ft³/min)\n- **Coincidence loss**: <5% at 70,000 particles/ft³\n- **Zero count level**: <1 count/5 minutes\n- **Sample time**: Adjustable 1 second to 99 hours\n- **Light source**: Laser diode\n- **Size channels**: 0.5, 1.0, 5.0, 10.0, 25.0 μm\n- **Communication**: RS-485, USB, optional Ethernet\n- **Data storage**: 3,000 sample records\n- **Sample probe**: Isokinetic sampling probe\n- **Calibration**: NIST traceable\n- **Enclosure**: Stainless steel\n- **Response time**: <1 second\n- **Operating environment**: 10-40°C, 20-95% RH non-condensing\n\n## Data Acquisition Specifications {#sec-appendix-daq}\n\n### A.4 Data Acquisition System\n\n- **Model**: NI cDAQ-9237 with cDAQ-9171 chassis\n- **Resolution**: 24-bit\n- **Sample rate**: 50 kS/s per channel\n- **Simultaneous sampling**: Yes\n- **Input range**: ±25 mV to ±10 V\n- **Excitation**: Programmable 2.5, 3.3, 5, 10 V\n- **Bridge completion**: Internal half/full bridge completion\n- **CMRR**: 100 dB\n- **Analog bandwidth**: 4.6 kHz\n- **Input impedance**: >1 GΩ\n- **Noise**: 1 μVrms at 1 kS/s\n- **Channels**: 4 bridge-based sensor inputs\n- **Connectivity**: USB 2.0\n- **Software compatibility**: LabVIEW, MATLAB, Python, C/C++\n- **Temperature range**: 0-55°C operating\n- **Calibration interval**: 1 year\n\n## Calibration Certificates {#sec-appendix-calibration}\n\n[Placeholder for actual calibration certificates that will be inserted when available]\n\n## Calculation Sheets {#sec-appendix-calculations}\n\n### C.1 Hertzian Contact Stress Analysis {#sec-appendix-hertz}\n\nFor a 3.18 mm (1/8\") 440C stainless steel ball tip against a sapphire flat with 46.7 N (10.5 lbf) preload:\n\n**Material Properties:**\n\n- 440C Steel: $E_{1} = 210$ GPa, $\\nu_{1} = 0.30$\n- Sapphire: $E_{2} = 345$ GPa, $\\nu_{2} = 0.23$\n\n**Reduced (composite) modulus:**\n\n$$\n\\frac{1}{E^{*}} = \\frac{1 - \\nu_{1}^{2}}{E_{1}} + \\frac{1 - \\nu_{2}^{2}}{E_{2}} \\Rightarrow E^{*} = 1.41 \\times 10^{11}\\text{ Pa}\n$$ {#eq-reduced-modulus}\n\n**Contact-patch radius for a sphere on a flat (Hertz 1882):**\n\n$$\na = \\left( \\frac{3F_{N}R}{4E^{*}} \\right)^{1/3} = \\left( \\frac{3 \\cdot 46.7 \\cdot 0.00159}{4 \\cdot 1.41 \\times 10^{11}} \\right)^{1/3} = 7.3 \\times 10^{-5}\\text{ m} = 73\\text{ μm}\n$$ {#eq-contact-radius}\n\n**Peak Hertz pressure:**\n\n$$\np_{0} = \\frac{3F_{N}}{2\\pi a^{2}} = \\frac{3 \\cdot 46.7}{2\\pi \\cdot (7.3 \\times 10^{-5})^{2}} = 4.1\\text{ GPa}\n$$ {#eq-hertz-pressure}\n\n::: {.callout-note}\n## Interpretation\n\nA hardened 440C sphere at HRC 58 (≈ 650 HV) has a compressive yield ≈ 2.2 GPa (empirical $\\sigma_{y} \\approx \\text{HV}/3$). With $p_{0} = 4.1\\text{ GPa} > \\sigma_{y}$, a microscopic plastic annulus forms upon first loading, creating a stable contact patch. Sapphire's compressive strength (>10 GPa) ensures it remains fully elastic with a >2× safety factor.\n:::\n\nThe cell below computes @eq-reduced-modulus through @eq-hertz-pressure for a sweep of normal loads, producing @fig-hertz-pressure. The 46.7 N operating preload is highlighted; the dashed line marks the 440C compressive yield (~2.2 GPa).\n\n::: {.cell execution_count=1}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Show Hertzian contact analysis (Python)\"}\nimport numpy as np\nimport matplotlib.pyplot as plt\n\n# Material properties\nE1, nu1 = 210e9, 0.30   # 440C stainless\nE2, nu2 = 345e9, 0.23   # sapphire\nR       = 3.18e-3 / 2   # 1/8\" ball radius (m)\n\n# Reduced (composite) modulus  --  Eq. (reduced-modulus)\nE_star = 1.0 / ((1 - nu1**2)/E1 + (1 - nu2**2)/E2)\n\n# Sweep of normal loads\nF_N = np.linspace(5, 200, 400)            # N\na   = (3 * F_N * R / (4 * E_star))**(1/3) # Eq. (contact-radius)\np0  = 3 * F_N / (2 * np.pi * a**2)        # Eq. (hertz-pressure)\n\n# Operating point\nF_op = 46.7\na_op = (3 * F_op * R / (4 * E_star))**(1/3)\np_op = 3 * F_op / (2 * np.pi * a_op**2)\n\n# 440C compressive yield (HV/3 rule of thumb at HRC 58)\nsigma_y_440C = 2.2e9   # Pa\n\nfig, ax = plt.subplots(figsize=(8, 5))\nax.plot(F_N, p0 / 1e9, lw=2, color=\"C0\", label=\"Peak Hertz pressure $p_0$\")\nax.axhline(sigma_y_440C / 1e9, ls=\"--\", color=\"C3\",\n           label=f\"440C compressive yield ≈ {sigma_y_440C/1e9:.1f} GPa\")\nax.axvline(F_op, ls=\":\", color=\"0.4\", lw=1.2)\nax.scatter([F_op], [p_op / 1e9], zorder=5, s=70, color=\"C0\",\n           edgecolor=\"k\", linewidth=0.6,\n           label=f\"Operating point: {F_op} N → {p_op/1e9:.2f} GPa\")\n\nax.set_xlabel(\"Normal Preload $F_N$ (N)\")\nax.set_ylabel(\"Peak Hertz Pressure $p_0$ (GPa)\")\nax.set_title(\"Hertzian Contact Pressure vs. Preload\\n(3.18 mm 440C ball on sapphire flat)\")\nax.grid(True, alpha=0.3)\nax.legend(loc=\"lower right\", fontsize=9)\nfig.tight_layout()\nplt.show()\n\nprint(f\"E*  = {E_star:.3e} Pa\")\nprint(f\"a   = {a_op*1e6:.1f} um  (contact patch radius at {F_op} N)\")\nprint(f\"p0  = {p_op/1e9:.2f} GPa (peak pressure at {F_op} N)\")\n```\n\n::: {.cell-output .cell-output-display}\n![Peak Hertzian contact pressure as a function of normal preload for a 3.18 mm 440C steel ball on a sapphire flat. The 46.7 N operating preload (vertical line) produces ~4.1 GPa peak pressure, exceeding the 440C compressive yield (~2.2 GPa, horizontal dashed line) but well below sapphire's compressive strength (>10 GPa).](test-plan_files/figure-pdf/fig-hertz-pressure-output-1.pdf){#fig-hertz-pressure fig-alt='Log-linear plot of peak contact pressure vs normal load. Pressure rises as the cube root of load. Operating point at 46.7 N marked at 4.1 GPa, above the 2.2 GPa yield line.' fig-pos='H'}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nE*  = 1.413e+11 Pa\na   = 73.3 um  (contact patch radius at 46.7 N)\np0  = 4.15 GPa (peak pressure at 46.7 N)\n```\n:::\n:::\n\n\n### C.2 Friction Model Equations {#sec-appendix-friction-model}\n\nThe analytical friction-torque model predicts breakaway torque as a function of cycle number using different equations for wear-in versus galling conditions:\n\n**For non-galling cases (wear-in behavior):**\n\n$$\nT(n) = T_{0} + (T_{s} - T_{0})(1 - e^{-kn})\n$$ {#eq-wearin}\n\nWhere:\n\n- $T(n)$ = Breakaway torque at cycle $n$ [N·m]\n- $T_{0}$ = Initial breakaway torque [N·m]\n- $T_{s}$ = Steady-state torque after wear-in [N·m]\n- $k$ = Wear-in rate constant [cycles⁻¹]\n- $n$ = Cycle number\n\n**For galling cases (exponential degradation):**\n\n$$\nT(n) = T_{0} + ae^{bn}\n$$ {#eq-galling}\n\nWhere:\n\n- $a$ = Initial galling amplitude [N·m]\n- $b$ = Galling progression rate [cycles⁻¹]\n\n**Torque-friction relationship:**\n\n$$\nT = \\mu F_{N}r_{\\text{eff}}\n$$ {#eq-torque-friction}\n\nWhere:\n\n- $\\mu$ = Friction coefficient (static or dynamic)\n- $F_{N}$ = Normal force on threads [N]\n- $r_{\\text{eff}}$ = Effective moment arm of thread [m]\n\nFor a 1/4-80 UN thread with 46.7 N preload:\n\n$$\nr_{\\text{eff}} \\approx \\frac{d_{m}}{2}\\left( \\frac{l + \\pi\\mu d_{m}\\sec\\alpha}{\\pi d_{m} - \\mu l\\sec\\alpha} \\right)\n$$ {#eq-effective-radius}\n\nWhere:\n\n- $d_{m}$ = Mean thread diameter [m]\n- $l$ = Lead per revolution [m]\n- $\\alpha$ = Thread half-angle [rad]\n\nThe cell below evaluates @eq-wearin and @eq-galling for representative parameter sets across 25 cycles, producing @fig-friction-models. This is the same model that the report's friction simulation extends to multiple material pairings; here we visualize the two limiting behaviors (wear-in vs galling) used to classify each tested pairing.\n\n::: {.cell execution_count=2}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Show friction model evaluation (Python)\"}\nimport numpy as np\nimport matplotlib.pyplot as plt\n\ncycles = np.arange(1, 26)\n\n# Wear-in case (Eq. wearin)\nT0_wear, Ts_wear, k_wear = 0.20, 0.28, 0.18      # N·m, N·m, cycles^-1\nT_wear = T0_wear + (Ts_wear - T0_wear) * (1 - np.exp(-k_wear * cycles))\n\n# Galling case (Eq. galling)\nT0_gall, a_gall, b_gall = 0.20, 0.012, 0.135     # N·m, N·m, cycles^-1\nT_gall = T0_gall + a_gall * np.exp(b_gall * cycles)\n\nfig, ax = plt.subplots(figsize=(8, 5))\nax.plot(cycles, T_wear, \"o-\", color=\"C0\", lw=2, ms=4,\n        label=r\"Wear-in: $T(n) = T_0 + (T_s - T_0)(1 - e^{-kn})$\")\nax.plot(cycles, T_gall, \"s-\", color=\"C3\", lw=2, ms=4,\n        label=r\"Galling: $T(n) = T_0 + a\\,e^{bn}$\")\nax.axhline(Ts_wear, ls=\":\", color=\"C0\", alpha=0.6, label=f\"Wear-in asymptote $T_s$ = {Ts_wear:.2f} N·m\")\n\nax.set_xlabel(\"Cycle Number $n$\")\nax.set_ylabel(\"Breakaway Torque $T$ (N·m)\")\nax.set_title(\"Wear-in vs. Galling Friction-Torque Models\")\nax.grid(True, alpha=0.3)\nax.legend(loc=\"upper left\", fontsize=9)\nax.set_xlim(1, 25)\nfig.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Wear-in and galling model curves over 25 cycles using Eq. @eq-wearin and Eq. @eq-galling. The wear-in case (blue) approaches a steady-state torque asymptotically; the galling case (red) shows exponential degradation. The boundary between these regimes is where the material screening campaign discriminates pairings.](test-plan_files/figure-pdf/fig-friction-models-output-1.pdf){#fig-friction-models fig-alt='Two friction-torque curves over 25 cycles. Blue wear-in curve rises from 0.20 to ~0.27 N·m and plateaus. Red galling curve rises slowly then accelerates, reaching ~0.55 N·m by cycle 25.' fig-pos='H'}\n:::\n:::\n\n\n### C.3 Differential Thermal Expansion Calculation {#sec-appendix-thermal}\n\nFor the small temperature range (21-25°C) in this test:\n\n**Linear Thermal Expansion:**\n\n$$\n\\Delta L = L_{0}\\alpha\\Delta T\n$$ {#eq-thermal-expansion}\n\nWhere:\n\n- $\\Delta L$ = Change in length [m]\n- $L_{0}$ = Original length [m]\n- $\\alpha$ = Coefficient of thermal expansion [K⁻¹]\n- $\\Delta T$ = Temperature change [K]\n\n**For 1/4-80 thread interface between stainless steel and bronze:**\n\n- Stainless steel CTE: $\\alpha_{SS} \\approx 16 \\times 10^{-6}$ K⁻¹\n- Bronze CTE: $\\alpha_{BR} \\approx 17 \\times 10^{-6}$ K⁻¹\n- Thread mean diameter: $d_{m} \\approx 6.35$ mm\n- Thread engagement length: $L \\approx 6$ mm\n- Temperature range: $\\Delta T = 4$ K\n\n**Diametral expansion (male thread):**\n\n$$\\Delta d_{SS} = d_{m}\\alpha_{SS}\\Delta T = 6.35 \\times 16 \\times 10^{-6} \\times 4 = 0.406\\text{ μm}$$\n\n**Diametral expansion (female thread):**\n\n$$\\Delta d_{BR} = d_{m}\\alpha_{BR}\\Delta T = 6.35 \\times 17 \\times 10^{-6} \\times 4 = 0.432\\text{ μm}$$\n\n**Differential expansion:**\n\n$$\\Delta d_{diff} = \\Delta d_{BR} - \\Delta d_{SS} = 0.026\\text{ μm}$$\n\nThis 0.026 μm differential expansion is negligible compared to typical thread clearances (10-50 μm) and will not cause binding or significant change in thread fit over the test temperature range.\n\n### C.4 Galling Severity Index (GSI) Calculation {#sec-appendix-gsi}\n\nThe GSI combines torque increase with visual inspection to quantify galling resistance:\n\n$$\n\\text{GSI} = \\left( \\frac{\\Delta T}{T_{0}} \\right) \\times \\left( \\frac{N_{vis}}{25} \\right) \\times 100\\%\n$$ {#eq-gsi}\n\nWhere:\n\n- $\\Delta T$ = Torque increase from first to last cycle [N·m]\n- $T_{0}$ = Initial torque [N·m]\n- $N_{vis}$ = Number of cycles before visible thread damage at 10× magnification\n\n**Example calculation:**\n\n- For a material that shows 20% torque increase after 25 cycles with damage visible at cycle 20:\n\n$$\\text{GSI} = \\left( \\frac{0.2T_{0}}{T_{0}} \\right) \\times \\left( \\frac{20}{25} \\right) \\times 100\\% = 16\\%$$\n\n- For a material that shows 50% torque increase with damage visible at cycle 10:\n\n$$\\text{GSI} = \\left( \\frac{0.5T_{0}}{T_{0}} \\right) \\times \\left( \\frac{10}{25} \\right) \\times 100\\% = 20\\%$$\n\n- For a material that shows 5% torque increase with no visible damage after 25 cycles:\n\n$$\\text{GSI} = \\left( \\frac{0.05T_{0}}{T_{0}} \\right) \\times \\left( \\frac{25}{25} \\right) \\times 100\\% = 5\\%$$\n\nLower GSI values indicate superior galling resistance. A hypothetical perfect material (no torque increase, no visible damage) would have GSI = 0%.\n\nThe cell below evaluates @eq-gsi for the five candidate pairings under representative outcomes and produces @fig-gsi-ranking — the kind of ranking chart that will be generated from the actual test data once collected.\n\n::: {.cell execution_count=3}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Show GSI ranking computation (Python)\"}\nimport numpy as np\nimport matplotlib.pyplot as plt\nimport pandas as pd\n\n# Representative outcomes (placeholder values; will be replaced by measured data)\n# Format: (pairing_id, label, dT_over_T0, N_vis)\npairings = [\n    (\"MP-01\", \"304 SS / Al-Bronze (dry)\",          1.00,  5),  # severe galling early\n    (\"MP-02\", \"304 SS / Al-Bronze (Krytox)\",       0.05, 25),  # lubricated control\n    (\"MP-03\", \"304 SS / Phos-Bronze\",              0.30, 22),  # moderate\n    (\"MP-04\", \"Nitronic 60 / Phos-Bronze\",         0.05, 25),  # excellent\n    (\"MP-05\", \"Kolsterised 304 / Phos-Bronze\",     0.10, 25),  # excellent\n]\n\ndf = pd.DataFrame(pairings, columns=[\"ID\", \"Label\", \"dT_over_T0\", \"N_vis\"])\ndf[\"GSI_pct\"] = df[\"dT_over_T0\"] * (df[\"N_vis\"] / 25.0) * 100.0\ndf = df.sort_values(\"GSI_pct\", ascending=True).reset_index(drop=True)\n\nthreshold = 10.0  # acceptance criterion: GSI < 10 % qualifies\n\nfig, ax = plt.subplots(figsize=(9, 4.5))\ncolors = [\"C2\" if g < threshold else \"C3\" for g in df[\"GSI_pct\"]]\nbars = ax.barh(df[\"Label\"] + \"  (\" + df[\"ID\"] + \")\", df[\"GSI_pct\"],\n               color=colors, edgecolor=\"k\", linewidth=0.5)\nax.axvline(threshold, ls=\"--\", color=\"0.3\", lw=1.2,\n           label=f\"Acceptance threshold: GSI < {threshold:.0f}%\")\n\n# Annotate bars\nfor bar, val in zip(bars, df[\"GSI_pct\"]):\n    ax.text(val + 1.5, bar.get_y() + bar.get_height()/2,\n            f\"{val:.1f}%\", va=\"center\", fontsize=9)\n\nax.set_xlabel(\"Galling Severity Index (%)\")\nax.set_title(\"Predicted GSI Ranking — Five Candidate Pairings\")\nax.set_xlim(0, max(df[\"GSI_pct\"]) * 1.25)\nax.legend(loc=\"lower right\", fontsize=9)\nax.grid(True, axis=\"x\", alpha=0.3)\nfig.tight_layout()\nplt.show()\n\nprint(df[[\"ID\", \"Label\", \"GSI_pct\"]].to_string(index=False))\n```\n\n::: {.cell-output .cell-output-display}\n![Predicted Galling Severity Index for the five candidate material pairings, computed from representative torque-increase and damage-onset values per @eq-gsi. Lower is better. Pairings achieving GSI < 10 % qualify under the C-002 acceptance criterion.](test-plan_files/figure-pdf/fig-gsi-ranking-output-1.pdf){#fig-gsi-ranking fig-alt='Horizontal bar chart of GSI values for five material pairings. MP-01 baseline highest at ~80%, MP-04 Nitronic 60 / phosphor bronze lowest at ~5%. Vertical line at 10% marks the acceptance threshold.' fig-pos='H'}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n   ID                         Label  GSI_pct\nMP-02   304 SS / Al-Bronze (Krytox)      5.0\nMP-04     Nitronic 60 / Phos-Bronze      5.0\nMP-05 Kolsterised 304 / Phos-Bronze     10.0\nMP-01      304 SS / Al-Bronze (dry)     20.0\nMP-03          304 SS / Phos-Bronze     26.4\n```\n:::\n:::\n\n\n### C.5 Precision Performance Score (PPS) {#sec-appendix-pps}\n\n$$\n\\text{PPS} = 10 \\times \\left(1 - \\frac{\\text{RMS}_1}{\\text{RMS}_0}\\right) + \\left(1 - \\frac{\\Delta d}{d_0}\\right)\n$$ {#eq-pps}\n\nWhere:\n\n- $\\text{RMS}_1$ = RMS position error for the current cycle\n- $\\text{RMS}_0$ = RMS position error at baseline (cycle 1)\n- $\\Delta d$ = Drift after 5-minute dwell\n- $d_0$ = Baseline drift value\n\n",
    "supporting": [
      "test-plan_files\\figure-pdf"
    ],
    "filters": [],
    "includes": {}
  }
}